"""Publication-style visualization for embedded vs verification comparison."""

from __future__ import annotations

from pathlib import Path
import argparse

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


OKABE_ITO = {
    "orange": "#E69F00",
    "sky_blue": "#56B4E9",
    "bluish_green": "#009E73",
    "blue": "#0072B2",
    "vermillion": "#D55E00",
    "reddish_purple": "#CC79A7",
    "black": "#000000",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot embedded-vs-verification speed/cost comparison."
    )
    parser.add_argument(
        "--trials-csv",
        type=str,
        default="sensitivity/results_new/embedding_vs_verification/instance10_emb_vs_ver_t5_i300_trials.csv",
        help="Path to trials CSV generated by benchmark script.",
    )
    parser.add_argument(
        "--pairs-csv",
        type=str,
        default="sensitivity/results_new/embedding_vs_verification/instance10_emb_vs_ver_t5_i300_pairs.csv",
        help="Path to pairs CSV generated by benchmark script.",
    )
    parser.add_argument(
        "--output-pdf",
        type=str,
        default="sensitivity/results_new/embedding_vs_verification/instance10_emb_vs_ver_t5_i300_figure.pdf",
        help="Output PDF path.",
    )
    parser.add_argument(
        "--output-png",
        type=str,
        default="sensitivity/results_new/embedding_vs_verification/instance10_emb_vs_ver_t5_i300_figure.png",
        help="Output PNG path.",
    )
    return parser.parse_args()


def _method_label(raw: str) -> str:
    if raw == "embedded":
        return "Embedded"
    if raw == "verification":
        return "Verification"
    return raw


def _clean_instance_name(text: str) -> str:
    return Path(text).stem


def main() -> None:
    args = parse_args()
    trials_path = Path(args.trials_csv)
    pairs_path = Path(args.pairs_csv)
    if not trials_path.exists():
        raise FileNotFoundError(f"Missing trials CSV: {trials_path}")
    if not pairs_path.exists():
        raise FileNotFoundError(f"Missing pairs CSV: {pairs_path}")

    trials = pd.read_csv(trials_path)
    pairs = pd.read_csv(pairs_path)

    trials["method_label"] = trials["method"].map(_method_label)
    trials["instance_stem"] = trials["instance"].map(_clean_instance_name)
    pairs["instance_stem"] = pairs["instance"].map(_clean_instance_name)

    method_order = ["Embedded", "Verification"]
    method_palette = {
        "Embedded": OKABE_ITO["sky_blue"],
        "Verification": OKABE_ITO["vermillion"],
    }

    plt.rcParams.update(
        {
            "font.family": "DejaVu Sans",
            "font.size": 9,
            "axes.labelsize": 10,
            "axes.titlesize": 10,
            "xtick.labelsize": 8,
            "ytick.labelsize": 8,
            "legend.fontsize": 8,
        }
    )
    sns.set_theme(style="ticks", context="paper")

    fig, axes = plt.subplots(2, 2, figsize=(10.0, 6.6))

    ax = axes[0, 0]
    sns.boxplot(
        data=trials,
        x="method_label",
        y="runtime_sec",
        order=method_order,
        palette=method_palette,
        width=0.55,
        fliersize=2.5,
        linewidth=1.0,
        ax=ax,
    )
    sns.stripplot(
        data=trials,
        x="method_label",
        y="runtime_sec",
        order=method_order,
        color=OKABE_ITO["black"],
        alpha=0.35,
        size=2.4,
        jitter=0.18,
        ax=ax,
    )
    ax.set_title("A. Runtime Distribution (All Runs)")
    ax.set_xlabel("")
    ax.set_ylabel("Runtime (s)")

    ax = axes[0, 1]
    sns.boxplot(
        data=trials,
        x="method_label",
        y="best_cost",
        order=method_order,
        palette=method_palette,
        width=0.55,
        fliersize=2.5,
        linewidth=1.0,
        ax=ax,
    )
    sns.stripplot(
        data=trials,
        x="method_label",
        y="best_cost",
        order=method_order,
        color=OKABE_ITO["black"],
        alpha=0.35,
        size=2.4,
        jitter=0.18,
        ax=ax,
    )
    ax.set_title("B. Best Cost Distribution (All Runs)")
    ax.set_xlabel("")
    ax.set_ylabel("Best Cost")

    per_instance = (
        pairs.groupby("instance_stem", as_index=False)
        .agg(
            speedup_median=("speedup_verification_over_embedded", "median"),
            cost_delta_median=("cost_delta_verification_minus_embedded", "median"),
        )
        .sort_values("instance_stem")
    )

    ax = axes[1, 0]
    sns.barplot(
        data=per_instance,
        x="instance_stem",
        y="speedup_median",
        color=OKABE_ITO["bluish_green"],
        edgecolor=OKABE_ITO["black"],
        linewidth=0.7,
        ax=ax,
    )
    ax.axhline(1.0, linestyle="--", linewidth=1.0, color=OKABE_ITO["reddish_purple"])
    ax.set_title("C. Median Speedup by Instance")
    ax.set_xlabel("Instance (10-customer)")
    ax.set_ylabel("Speedup = T_embedded / T_verification")
    ax.tick_params(axis="x", rotation=55)

    ax = axes[1, 1]
    sns.barplot(
        data=per_instance,
        x="instance_stem",
        y="cost_delta_median",
        color=OKABE_ITO["orange"],
        edgecolor=OKABE_ITO["black"],
        linewidth=0.7,
        ax=ax,
    )
    ax.axhline(0.0, linestyle="--", linewidth=1.0, color=OKABE_ITO["reddish_purple"])
    ax.set_title("D. Median Cost Delta by Instance")
    ax.set_xlabel("Instance (10-customer)")
    ax.set_ylabel("Cost Delta = Verification - Embedded")
    ax.tick_params(axis="x", rotation=55)

    for axis in axes.flat:
        axis.spines["top"].set_visible(False)
        axis.spines["right"].set_visible(False)

    fig.suptitle("Embedded vs Verification on 10-Customer Instances", fontsize=11, y=0.995)
    fig.tight_layout()

    output_pdf = Path(args.output_pdf)
    output_png = Path(args.output_png)
    output_pdf.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_pdf, dpi=300, bbox_inches="tight")
    fig.savefig(output_png, dpi=300, bbox_inches="tight")
    print(f"Saved PDF: {output_pdf}")
    print(f"Saved PNG: {output_png}")


if __name__ == "__main__":
    main()
