"""
Visualize and analyze Instance10 2same2flexible results without external plotting deps.

Outputs (SVG + CSV + Markdown):
- instance10_2same2flex_saving_rank.svg
- instance10_2same2flex_route_before_after.svg
- instance10_2same2flex_route_diff_metrics.csv
- instance10_2same2flex_route_analysis.md
"""

from __future__ import annotations

from dataclasses import dataclass
import argparse
import ast
import csv
import json
import math
import re
from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple


ROOT_DIR = Path(__file__).resolve().parents[2]
DEFAULT_RESULTS_DIR = ROOT_DIR / "sensitivity" / "results_new" / "drone_flexibility"
DEFAULT_INPUT_CSV = DEFAULT_RESULTS_DIR / "docking_flexibility_instance10_2same2flex_best_by_instance.csv"


@dataclass
class RouteAnalysis:
    instance: str
    same_seed: int | None
    flex_seed: int | None
    same_cost: float
    flex_cost: float
    saving_pct: float
    same_drone_tasks: int
    flex_drone_tasks: int
    same_cross_truck_tasks: int
    flex_cross_truck_tasks: int
    truck_edge_symdiff: int
    drone_customer_shift_to_flex: int
    drone_customer_shift_from_flex: int
    representative_score: float


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot flexible-docking route effects from paired same/flexible CSV.")
    parser.add_argument(
        "--input-csv",
        type=str,
        default=str(DEFAULT_INPUT_CSV),
        help="Input best_by_instance CSV generated by instance10_2same2flex.py",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=str(DEFAULT_RESULTS_DIR),
        help="Output directory.",
    )
    parser.add_argument(
        "--output-prefix",
        type=str,
        default="instance10_2same2flex",
        help="Prefix for generated output files.",
    )
    parser.add_argument(
        "--dataset-label",
        type=str,
        default="",
        help="Dataset label used in chart/report titles (default: infer from instance names).",
    )
    return parser.parse_args()


def _to_float(value: Any) -> float:
    try:
        val = float(value)
    except (TypeError, ValueError):
        return math.nan
    return val


def _to_int(value: Any) -> int | None:
    if value is None or value == "":
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _load_json_payload(text: str) -> List[Dict[str, Any]]:
    if not text:
        return []
    try:
        payload = json.loads(text)
        return payload if isinstance(payload, list) else []
    except json.JSONDecodeError:
        try:
            payload = ast.literal_eval(text)
            return payload if isinstance(payload, list) else []
        except (SyntaxError, ValueError):
            return []


def _instance_stem(path_text: str) -> str:
    return Path(path_text).stem if path_text else path_text


def infer_dataset_label(rows: List[Dict[str, Any]]) -> str:
    sizes: set[int] = set()
    for row in rows:
        stem = _instance_stem(str(row.get("instance", "")))
        match = re.match(r"R_\d+_(\d+)_\d+", stem)
        if not match:
            continue
        try:
            sizes.add(int(match.group(1)))
        except ValueError:
            continue
    if len(sizes) == 1:
        n = next(iter(sizes))
        return f"Instance{n} Same vs Flexible"
    if len(sizes) > 1:
        return "Mixed Instances Same vs Flexible"
    return "Same vs Flexible"


def load_best_rows(csv_path: Path) -> List[Dict[str, Any]]:
    rows: list[Dict[str, Any]] = []
    with csv_path.open("r", newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            rows.append(row)
    return rows


def parse_instance_coordinates(instance_path: Path) -> Dict[int, Tuple[float, float]]:
    coords: dict[int, tuple[float, float]] = {}
    in_customer_section = False
    with instance_path.open("r", encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            if not line:
                continue
            if line == "CUSTOMER INFORMATION":
                in_customer_section = True
                continue
            if in_customer_section and line in {"Distance For Drone", "Distance For Truck", "VEHICLE INFORMATION"}:
                break
            if not in_customer_section:
                continue
            if line.lower().startswith("id"):
                continue
            parts = line.replace("\t", " ").split()
            if len(parts) < 3:
                continue
            try:
                node = int(parts[0])
                x = float(parts[1])
                y = float(parts[2])
            except ValueError:
                continue
            coords[node] = (x, y)
    return coords


def build_truck_edges(routes: Iterable[Dict[str, Any]]) -> set[Tuple[int, int]]:
    edges: set[tuple[int, int]] = set()
    for route in routes:
        nodes = route.get("nodes", [])
        if not isinstance(nodes, list):
            continue
        for i in range(len(nodes) - 1):
            try:
                u = int(nodes[i])
                v = int(nodes[i + 1])
            except (TypeError, ValueError):
                continue
            edges.add((u, v))
    return edges


def extract_drone_customers(tasks: Iterable[Dict[str, Any]]) -> set[int]:
    customers: set[int] = set()
    for task in tasks:
        payload = task.get("customers", [])
        if not isinstance(payload, list):
            continue
        for node in payload:
            try:
                customers.add(int(node))
            except (TypeError, ValueError):
                continue
    return customers


def count_cross_truck_tasks(tasks: Iterable[Dict[str, Any]]) -> int:
    total = 0
    for task in tasks:
        launch_truck = task.get("launch_truck")
        land_truck = task.get("land_truck")
        if launch_truck is None or land_truck is None:
            continue
        try:
            if int(launch_truck) != int(land_truck):
                total += 1
        except (TypeError, ValueError):
            continue
    return total


def analyze_row(row: Dict[str, Any]) -> RouteAnalysis:
    same_routes = _load_json_payload(row.get("same_truck_routes", ""))
    same_tasks = _load_json_payload(row.get("same_drone_tasks", ""))
    flex_routes = _load_json_payload(row.get("flexible_truck_routes", ""))
    flex_tasks = _load_json_payload(row.get("flexible_drone_tasks", ""))

    same_edges = build_truck_edges(same_routes)
    flex_edges = build_truck_edges(flex_routes)
    truck_edge_symdiff = len(same_edges.symmetric_difference(flex_edges))

    same_drone_customers = extract_drone_customers(same_tasks)
    flex_drone_customers = extract_drone_customers(flex_tasks)
    to_flex = len(flex_drone_customers - same_drone_customers)
    from_flex = len(same_drone_customers - flex_drone_customers)

    same_cross = count_cross_truck_tasks(same_tasks)
    flex_cross = count_cross_truck_tasks(flex_tasks)

    saving_pct = _to_float(row.get("flexible_saving_vs_same"))
    saving_component = max(0.0, saving_pct) if math.isfinite(saving_pct) else 0.0

    score = (
        saving_component * 10.0
        + max(0, flex_cross - same_cross) * 2.5
        + to_flex * 1.5
        + truck_edge_symdiff * 0.2
    )

    return RouteAnalysis(
        instance=row.get("instance", ""),
        same_seed=_to_int(row.get("same_seed")),
        flex_seed=_to_int(row.get("flex_seed")),
        same_cost=_to_float(row.get("same_cost")),
        flex_cost=_to_float(row.get("flexible_cost")),
        saving_pct=saving_pct,
        same_drone_tasks=len(same_tasks),
        flex_drone_tasks=len(flex_tasks),
        same_cross_truck_tasks=same_cross,
        flex_cross_truck_tasks=flex_cross,
        truck_edge_symdiff=truck_edge_symdiff,
        drone_customer_shift_to_flex=to_flex,
        drone_customer_shift_from_flex=from_flex,
        representative_score=score,
    )


def choose_representative(analyses: List[RouteAnalysis]) -> RouteAnalysis:
    """
    Pick a case that best highlights flexible mechanism:
    1) flexible introduces cross-truck retrieval
    2) truck-route change is as small as possible
    3) among ties, prefer larger cross-truck increase and better saving
    """
    cross_candidates = [
        item for item in analyses
        if item.flex_cross_truck_tasks > item.same_cross_truck_tasks
    ]
    if not cross_candidates:
        return max(analyses, key=lambda item: item.saving_pct)

    positive_cross = [item for item in cross_candidates if item.saving_pct >= 0]
    strong_saving = [item for item in positive_cross if item.saving_pct >= 2.0]
    if strong_saving:
        pool = strong_saving
    elif positive_cross:
        pool = positive_cross
    else:
        pool = cross_candidates

    return min(
        pool,
        key=lambda item: (
            item.truck_edge_symdiff,
            -(item.flex_cross_truck_tasks - item.same_cross_truck_tasks),
            -(item.saving_pct if math.isfinite(item.saving_pct) else -math.inf),
            item.drone_customer_shift_to_flex + item.drone_customer_shift_from_flex,
        )
    )


def choose_top_saving(analyses: List[RouteAnalysis]) -> RouteAnalysis:
    return max(analyses, key=lambda item: item.saving_pct)


def write_metrics_csv(analyses: Iterable[RouteAnalysis], out_path: Path) -> None:
    fieldnames = [
        "instance",
        "same_seed",
        "flex_seed",
        "same_cost",
        "flex_cost",
        "saving_pct",
        "same_drone_tasks",
        "flex_drone_tasks",
        "same_cross_truck_tasks",
        "flex_cross_truck_tasks",
        "truck_edge_symdiff",
        "drone_customer_shift_to_flex",
        "drone_customer_shift_from_flex",
        "representative_score",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for item in analyses:
            writer.writerow({
                "instance": item.instance,
                "same_seed": item.same_seed,
                "flex_seed": item.flex_seed,
                "same_cost": item.same_cost,
                "flex_cost": item.flex_cost,
                "saving_pct": item.saving_pct,
                "same_drone_tasks": item.same_drone_tasks,
                "flex_drone_tasks": item.flex_drone_tasks,
                "same_cross_truck_tasks": item.same_cross_truck_tasks,
                "flex_cross_truck_tasks": item.flex_cross_truck_tasks,
                "truck_edge_symdiff": item.truck_edge_symdiff,
                "drone_customer_shift_to_flex": item.drone_customer_shift_to_flex,
                "drone_customer_shift_from_flex": item.drone_customer_shift_from_flex,
                "representative_score": item.representative_score,
            })


def _svg_header(width: int, height: int) -> List[str]:
    return [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        "<style>",
        "text { font-family: Arial, sans-serif; fill: #111; }",
        ".title { font-size: 16px; font-weight: bold; }",
        ".label { font-size: 12px; }",
        ".tick { font-size: 10px; }",
        "</style>",
    ]


def _svg_footer() -> List[str]:
    return ["</svg>"]


def _line(x1: float, y1: float, x2: float, y2: float, color: str, width: float = 1.0, dash: bool = False) -> str:
    dash_attr = ' stroke-dasharray="4,3"' if dash else ""
    return (
        f'<line x1="{x1:.2f}" y1="{y1:.2f}" x2="{x2:.2f}" y2="{y2:.2f}" '
        f'stroke="{color}" stroke-width="{width}"{dash_attr}/>'
    )


def _polyline(points: List[Tuple[float, float]], color: str, width: float = 1.2, dash: bool = False) -> str:
    dash_attr = ' stroke-dasharray="5,4"' if dash else ""
    path = " ".join(f"{x:.2f},{y:.2f}" for x, y in points)
    return (
        f'<polyline fill="none" stroke="{color}" stroke-width="{width}"{dash_attr} '
        f'points="{path}"/>'
    )


def _arrow_head(
    x1: float,
    y1: float,
    x2: float,
    y2: float,
    color: str,
    size: float = 7.0,
    width: float = 5.0,
) -> str:
    dx = x2 - x1
    dy = y2 - y1
    length = math.hypot(dx, dy)
    if length < 1e-6:
        return ""

    ux = dx / length
    uy = dy / length
    base_x = x2 - ux * size
    base_y = y2 - uy * size
    px = -uy
    py = ux
    half_w = width / 2.0

    left_x = base_x + px * half_w
    left_y = base_y + py * half_w
    right_x = base_x - px * half_w
    right_y = base_y - py * half_w

    points = (
        f"{x2:.2f},{y2:.2f} "
        f"{left_x:.2f},{left_y:.2f} "
        f"{right_x:.2f},{right_y:.2f}"
    )
    return f'<polygon points="{points}" fill="{color}" stroke="{color}" stroke-width="0.6"/>'


def _draw_path_with_arrows(
    svg: List[str],
    points: List[Tuple[float, float]],
    color: str,
    width: float,
    *,
    dash: bool = False,
    arrow_size: float = 7.0,
    arrow_width: float = 5.0,
) -> None:
    if len(points) < 2:
        return
    for i in range(len(points) - 1):
        x1, y1 = points[i]
        x2, y2 = points[i + 1]
        svg.append(_line(x1, y1, x2, y2, color, width, dash=dash))
        arrow = _arrow_head(x1, y1, x2, y2, color, size=arrow_size, width=arrow_width)
        if arrow:
            svg.append(arrow)


def _circle(x: float, y: float, r: float, fill: str, stroke: str = "#000", width: float = 1.0) -> str:
    return (
        f'<circle cx="{x:.2f}" cy="{y:.2f}" r="{r:.2f}" fill="{fill}" '
        f'stroke="{stroke}" stroke-width="{width}"/>'
    )


def _rect(x: float, y: float, w: float, h: float, fill: str, stroke: str = "#000", width: float = 1.0) -> str:
    return (
        f'<rect x="{x:.2f}" y="{y:.2f}" width="{w:.2f}" height="{h:.2f}" fill="{fill}" '
        f'stroke="{stroke}" stroke-width="{width}"/>'
    )


def _text(x: float, y: float, value: str, cls: str = "label", anchor: str = "middle") -> str:
    return f'<text x="{x:.2f}" y="{y:.2f}" class="{cls}" text-anchor="{anchor}">{value}</text>'


def _transform_point(
    x: float,
    y: float,
    x_min: float,
    x_max: float,
    y_min: float,
    y_max: float,
    panel_x: float,
    panel_y: float,
    panel_w: float,
    panel_h: float,
    padding: float = 28.0,
) -> Tuple[float, float]:
    inner_x = panel_x + padding
    inner_y = panel_y + padding
    inner_w = panel_w - 2 * padding
    inner_h = panel_h - 2 * padding
    if math.isclose(x_max, x_min):
        tx = inner_x + inner_w / 2
    else:
        tx = inner_x + (x - x_min) / (x_max - x_min) * inner_w
    if math.isclose(y_max, y_min):
        ty = inner_y + inner_h / 2
    else:
        ty = inner_y + inner_h - (y - y_min) / (y_max - y_min) * inner_h
    return tx, ty


def plot_saving_ranking_svg(
    analyses: List[RouteAnalysis],
    out_path: Path,
    dataset_label: str,
) -> None:
    ranked = sorted(analyses, key=lambda item: item.saving_pct, reverse=True)
    if not ranked:
        return

    width = 1200
    height = 560
    left = 70
    right = 30
    top = 60
    bottom = 120
    inner_x = left
    inner_y = top
    inner_w = width - left - right
    inner_h = height - top - bottom

    values = [item.saving_pct for item in ranked]
    v_min = min(min(values), 0.0)
    v_max = max(max(values), 0.0)
    if math.isclose(v_min, v_max):
        v_min -= 1.0
        v_max += 1.0
    pad = (v_max - v_min) * 0.12
    v_min -= pad
    v_max += pad

    def to_y(v: float) -> float:
        return inner_y + (v_max - v) / (v_max - v_min) * inner_h

    svg: list[str] = []
    svg.extend(_svg_header(width, height))
    svg.append(_text(width / 2, 28, f"{dataset_label} Saving Ranking", "title"))
    svg.append(_line(inner_x, inner_y, inner_x, inner_y + inner_h, "#333", 1.2))
    svg.append(_line(inner_x, inner_y + inner_h, inner_x + inner_w, inner_y + inner_h, "#333", 1.2))
    zero_y = to_y(0.0)
    svg.append(_line(inner_x, zero_y, inner_x + inner_w, zero_y, "#777", 1.0))

    for tick in [v_min, 0.0, v_max]:
        y = to_y(tick)
        svg.append(_line(inner_x, y, inner_x + inner_w, y, "#d0d0d0", 0.7))
        svg.append(_text(inner_x - 8, y + 3, f"{tick:.1f}", "tick", "end"))

    n = len(ranked)
    group_w = inner_w / n
    bar_w = group_w * 0.64
    for i, item in enumerate(ranked):
        x_center = inner_x + (i + 0.5) * group_w
        y_val = to_y(item.saving_pct)
        y0 = to_y(0.0)
        bar_y = min(y_val, y0)
        bar_h = abs(y_val - y0)
        color = "#0A9396" if i == 0 else "#3A86FF"
        svg.append(_rect(x_center - bar_w / 2, bar_y, bar_w, bar_h, color, stroke="#1f2937", width=0.7))
        stem = _instance_stem(item.instance)
        svg.append(_text(x_center, inner_y + inner_h + 44, stem, "tick"))
        label_y = bar_y - 6 if item.saving_pct >= 0 else bar_y + bar_h + 12
        label = f"{item.saving_pct:.1f}% (S{item.same_seed}/F{item.flex_seed})"
        svg.append(_text(x_center, label_y, label, "tick"))

    avg = sum(values) / len(values)
    avg_y = to_y(avg)
    svg.append(_line(inner_x, avg_y, inner_x + inner_w, avg_y, "#E76F51", 1.6, dash=True))
    svg.append(_text(inner_x + 80, avg_y - 6, f"Avg: {avg:.2f}%", "tick", "start"))
    svg.append(_text(18, inner_y + inner_h / 2, "Saving %", "label"))

    svg.extend(_svg_footer())
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(svg), encoding="utf-8")


def _draw_solution_panel(
    svg: List[str],
    panel_x: float,
    panel_y: float,
    panel_w: float,
    panel_h: float,
    title: str,
    coords: Dict[int, Tuple[float, float]],
    truck_routes: List[Dict[str, Any]],
    drone_tasks: List[Dict[str, Any]],
) -> None:
    svg.append(_rect(panel_x, panel_y, panel_w, panel_h, "#fafafa", stroke="#d0d0d0", width=1.0))
    svg.append(_text(panel_x + panel_w / 2, panel_y + 20, title, "label"))

    if not coords:
        svg.append(_text(panel_x + panel_w / 2, panel_y + panel_h / 2, "No coordinates", "label"))
        return

    xs = [p[0] for p in coords.values()]
    ys = [p[1] for p in coords.values()]
    x_min, x_max = min(xs), max(xs)
    y_min, y_max = min(ys), max(ys)

    truck_palette = ["#3A86FF", "#FB8500", "#8338EC", "#06D6A0", "#EF476F"]
    truck_colors: dict[int, str] = {}
    for route in truck_routes:
        try:
            tid = int(route.get("truck_id", 0))
        except (TypeError, ValueError):
            tid = 0
        if tid not in truck_colors:
            truck_colors[tid] = truck_palette[len(truck_colors) % len(truck_palette)]

    # Truck routes
    for route in truck_routes:
        nodes = route.get("nodes", [])
        if not isinstance(nodes, list) or len(nodes) < 2:
            continue
        try:
            tid = int(route.get("truck_id", 0))
        except (TypeError, ValueError):
            tid = 0
        color = truck_colors.get(tid, "#3A86FF")
        points: list[tuple[float, float]] = []
        for node in nodes:
            if node not in coords:
                continue
            tx, ty = _transform_point(
                coords[node][0], coords[node][1],
                x_min, x_max, y_min, y_max,
                panel_x, panel_y, panel_w, panel_h
            )
            points.append((tx, ty))
        _draw_path_with_arrows(
            svg,
            points,
            color=color,
            width=2.2,
            dash=False,
            arrow_size=8.0,
            arrow_width=6.0,
        )

    # Drone tasks
    for task in drone_tasks:
        launch_node = task.get("launch_node")
        retrieve_node = task.get("retrieve_node")
        customers = task.get("customers", [])
        if not isinstance(customers, list):
            customers = []
        if launch_node is None or retrieve_node is None:
            continue
        try:
            path_nodes = [int(launch_node)] + [int(c) for c in customers] + [int(retrieve_node)]
        except (TypeError, ValueError):
            continue

        launch_truck = task.get("launch_truck")
        land_truck = task.get("land_truck")
        cross = (
            launch_truck is not None and land_truck is not None
            and str(launch_truck) != str(land_truck)
        )
        color = "#D62828" if cross else "#5E548E"
        points: list[tuple[float, float]] = []
        for node in path_nodes:
            if node not in coords:
                continue
            points.append(_transform_point(
                coords[node][0], coords[node][1],
                x_min, x_max, y_min, y_max,
                panel_x, panel_y, panel_w, panel_h
            ))
        _draw_path_with_arrows(
            svg,
            points,
            color=color,
            width=1.2 if not cross else 1.8,
            dash=True,
            arrow_size=7.0 if not cross else 8.0,
            arrow_width=4.5 if not cross else 5.5,
        )

    # Nodes
    sorted_nodes = sorted(coords.keys())
    depot_start = min(sorted_nodes)
    depot_end = max(sorted_nodes)
    for node in sorted_nodes:
        tx, ty = _transform_point(
            coords[node][0], coords[node][1],
            x_min, x_max, y_min, y_max,
            panel_x, panel_y, panel_w, panel_h
        )
        if node == depot_start:
            svg.append(_rect(tx - 5, ty - 5, 10, 10, "#2A9D8F"))
        elif node == depot_end and depot_end != depot_start:
            svg.append(_rect(tx - 5, ty - 5, 10, 10, "#F4A261"))
        else:
            svg.append(_circle(tx, ty, 4.0, "#F8F9FA", stroke="#222", width=1.0))
        svg.append(_text(tx + 6, ty - 4, str(node), "tick", "start"))


def plot_route_before_after_svg(target_row: Dict[str, Any], analysis: RouteAnalysis, out_path: Path) -> None:
    instance_path = ROOT_DIR / target_row["instance"]
    coords = parse_instance_coordinates(instance_path)

    same_routes = _load_json_payload(target_row.get("same_truck_routes", ""))
    same_tasks = _load_json_payload(target_row.get("same_drone_tasks", ""))
    flex_routes = _load_json_payload(target_row.get("flexible_truck_routes", ""))
    flex_tasks = _load_json_payload(target_row.get("flexible_drone_tasks", ""))

    width = 1400
    height = 700
    pad = 30
    gap = 30
    panel_w = (width - 2 * pad - gap)
    panel_w /= 2
    panel_h = height - 2 * pad - 40

    svg: list[str] = []
    svg.extend(_svg_header(width, height))

    title = (
        f"Most Representative Flexible Case: {_instance_stem(analysis.instance)} | "
        f"saving={analysis.saving_pct:.2f}% | score={analysis.representative_score:.2f}"
    )
    svg.append(_text(width / 2, 24, title, "title"))

    _draw_solution_panel(
        svg,
        pad,
        pad + 20,
        panel_w,
        panel_h,
        f"Same-Truck (Cost={analysis.same_cost:.2f})",
        coords,
        same_routes,
        same_tasks,
    )
    _draw_solution_panel(
        svg,
        pad + panel_w + gap,
        pad + 20,
        panel_w,
        panel_h,
        f"Flexible (Cost={analysis.flex_cost:.2f})",
        coords,
        flex_routes,
        flex_tasks,
    )

    legend_y = height - 18
    svg.append(_line(40, legend_y, 90, legend_y, "#3A86FF", 2.2))
    svg.append(_text(95, legend_y + 3, "Truck route", "tick", "start"))
    svg.append(_line(200, legend_y, 250, legend_y, "#5E548E", 1.2, dash=True))
    svg.append(_text(255, legend_y + 3, "Drone task", "tick", "start"))
    svg.append(_line(340, legend_y, 390, legend_y, "#D62828", 1.8, dash=True))
    svg.append(_text(395, legend_y + 3, "Cross-truck task", "tick", "start"))
    svg.append(_text(540, legend_y + 3, "Arrowheads indicate direction", "tick", "start"))

    svg.extend(_svg_footer())
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(svg), encoding="utf-8")


def _format_case_tag(case_name: str, analysis: RouteAnalysis) -> str:
    return (
        f"{case_name}: {_instance_stem(analysis.instance)} | "
        f"same={analysis.same_cost:.2f} | flex={analysis.flex_cost:.2f} | "
        f"saving={analysis.saving_pct:.2f}% | same_seed={analysis.same_seed} | flex_seed={analysis.flex_seed}"
    )


def plot_dual_case_comparison_svg(
    top_row: Dict[str, Any],
    top_analysis: RouteAnalysis,
    rep_row: Dict[str, Any],
    rep_analysis: RouteAnalysis,
    out_path: Path,
    dataset_label: str,
) -> None:
    width = 1460
    height = 1320
    outer_pad = 30
    row_gap = 40
    col_gap = 30

    row_title_h = 24
    row_block_h = (height - 2 * outer_pad - row_gap) / 2
    panel_h = row_block_h - row_title_h - 10
    panel_w = (width - 2 * outer_pad - col_gap) / 2

    row1_y = outer_pad
    row2_y = outer_pad + row_block_h + row_gap
    panel1_y = row1_y + row_title_h + 8
    panel2_y = row2_y + row_title_h + 8

    top_instance_path = ROOT_DIR / top_row["instance"]
    rep_instance_path = ROOT_DIR / rep_row["instance"]

    top_coords = parse_instance_coordinates(top_instance_path)
    rep_coords = parse_instance_coordinates(rep_instance_path)

    top_same_routes = _load_json_payload(top_row.get("same_truck_routes", ""))
    top_same_tasks = _load_json_payload(top_row.get("same_drone_tasks", ""))
    top_flex_routes = _load_json_payload(top_row.get("flexible_truck_routes", ""))
    top_flex_tasks = _load_json_payload(top_row.get("flexible_drone_tasks", ""))

    rep_same_routes = _load_json_payload(rep_row.get("same_truck_routes", ""))
    rep_same_tasks = _load_json_payload(rep_row.get("same_drone_tasks", ""))
    rep_flex_routes = _load_json_payload(rep_row.get("flexible_truck_routes", ""))
    rep_flex_tasks = _load_json_payload(rep_row.get("flexible_drone_tasks", ""))

    svg: list[str] = []
    svg.extend(_svg_header(width, height))
    svg.append(_text(width / 2, 22, f"{dataset_label} Flexible Strategy Comparison", "title"))

    # Row 1: highest saving
    svg.append(_text(width / 2, row1_y + 18, _format_case_tag("Case A (Highest Saving)", top_analysis), "label"))
    _draw_solution_panel(
        svg,
        outer_pad,
        panel1_y,
        panel_w,
        panel_h,
        f"Same-Truck (Cost={top_analysis.same_cost:.2f})",
        top_coords,
        top_same_routes,
        top_same_tasks,
    )
    _draw_solution_panel(
        svg,
        outer_pad + panel_w + col_gap,
        panel1_y,
        panel_w,
        panel_h,
        f"Flexible (Cost={top_analysis.flex_cost:.2f})",
        top_coords,
        top_flex_routes,
        top_flex_tasks,
    )

    # Row 2: most representative flexible mechanism
    svg.append(_text(width / 2, row2_y + 18, _format_case_tag("Case B (Flexible Mechanism)", rep_analysis), "label"))
    _draw_solution_panel(
        svg,
        outer_pad,
        panel2_y,
        panel_w,
        panel_h,
        f"Same-Truck (Cost={rep_analysis.same_cost:.2f})",
        rep_coords,
        rep_same_routes,
        rep_same_tasks,
    )
    _draw_solution_panel(
        svg,
        outer_pad + panel_w + col_gap,
        panel2_y,
        panel_w,
        panel_h,
        f"Flexible (Cost={rep_analysis.flex_cost:.2f})",
        rep_coords,
        rep_flex_routes,
        rep_flex_tasks,
    )

    legend_y = height - 18
    svg.append(_line(50, legend_y, 100, legend_y, "#3A86FF", 2.2))
    svg.append(_text(105, legend_y + 3, "Truck route", "tick", "start"))
    svg.append(_line(210, legend_y, 260, legend_y, "#5E548E", 1.2, dash=True))
    svg.append(_text(265, legend_y + 3, "Drone task", "tick", "start"))
    svg.append(_line(350, legend_y, 400, legend_y, "#D62828", 1.8, dash=True))
    svg.append(_text(405, legend_y + 3, "Cross-truck task", "tick", "start"))
    svg.append(_text(550, legend_y + 3, "Arrowheads indicate direction", "tick", "start"))

    svg.extend(_svg_footer())
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(svg), encoding="utf-8")


def _format_cross_tasks(tasks: List[Dict[str, Any]]) -> List[str]:
    lines: list[str] = []
    for task in tasks:
        launch_truck = task.get("launch_truck")
        land_truck = task.get("land_truck")
        if launch_truck is None or land_truck is None:
            continue
        if str(launch_truck) == str(land_truck):
            continue
        launch_node = task.get("launch_node")
        retrieve_node = task.get("retrieve_node")
        customers = task.get("customers", [])
        customer_text = ",".join(str(c) for c in customers) if isinstance(customers, list) else ""
        lines.append(f"T{launch_truck}@{launch_node} -> [{customer_text}] -> T{land_truck}@{retrieve_node}")
    return lines


def write_markdown_report(
    analyses: List[RouteAnalysis],
    target_row: Dict[str, Any],
    target_analysis: RouteAnalysis,
    out_path: Path,
    dataset_label: str,
) -> None:
    ranked = sorted(analyses, key=lambda item: item.saving_pct, reverse=True)
    flex_tasks = _load_json_payload(target_row.get("flexible_drone_tasks", ""))
    cross_lines = _format_cross_tasks(flex_tasks)

    lines: list[str] = []
    lines.append(f"# {dataset_label} Flexible Docking Route Analysis")
    lines.append("")
    lines.append("## Most Representative Case")
    lines.append(f"- Instance: `{_instance_stem(target_analysis.instance)}`")
    lines.append(f"- same seed: `{target_analysis.same_seed}`, flex seed: `{target_analysis.flex_seed}`")
    lines.append(f"- same cost: `{target_analysis.same_cost:.4f}`")
    lines.append(f"- flex cost: `{target_analysis.flex_cost:.4f}`")
    lines.append(f"- saving: `{target_analysis.saving_pct:.2f}%`")
    lines.append("- selection rule: `cross-truck appears` + `minimal truck-route change`")
    lines.append("")
    lines.append("## Route Change Signals")
    lines.append(f"- Truck edge symmetric difference: `{target_analysis.truck_edge_symdiff}`")
    lines.append(f"- Drone tasks: `{target_analysis.same_drone_tasks}` -> `{target_analysis.flex_drone_tasks}`")
    lines.append(
        f"- Cross-truck retrieval tasks: `{target_analysis.same_cross_truck_tasks}` -> "
        f"`{target_analysis.flex_cross_truck_tasks}`"
    )
    lines.append(f"- Customers shifted to drone in flexible: `{target_analysis.drone_customer_shift_to_flex}`")
    lines.append(f"- Customers shifted away from drone in flexible: `{target_analysis.drone_customer_shift_from_flex}`")
    lines.append("")
    lines.append("## Key Cross-Truck Tasks In Flexible")
    if cross_lines:
        for item in cross_lines:
            lines.append(f"- {item}")
    else:
        lines.append("- None")
    lines.append("")
    lines.append("## Top-3 Savings")
    for item in ranked[:3]:
        lines.append(
            f"- `{_instance_stem(item.instance)}`: {item.saving_pct:.2f}% "
            f"(same seed={item.same_seed}, flex seed={item.flex_seed})"
        )
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()
    input_csv = Path(args.input_csv)
    output_dir = Path(args.output_dir)
    output_prefix = args.output_prefix

    if not input_csv.exists():
        raise FileNotFoundError(f"Input CSV not found: {input_csv}")

    rows = load_best_rows(input_csv)
    if not rows:
        raise ValueError("Input CSV is empty.")
    dataset_label = args.dataset_label.strip() or infer_dataset_label(rows)

    analyses = [analyze_row(row) for row in rows]
    top_saving_analysis = choose_top_saving(analyses)
    target_analysis = choose_representative(analyses)
    top_saving_row = next(row for row in rows if row.get("instance") == top_saving_analysis.instance)
    target_row = next(row for row in rows if row.get("instance") == target_analysis.instance)

    metrics_csv = output_dir / f"{output_prefix}_route_diff_metrics.csv"
    saving_svg = output_dir / f"{output_prefix}_saving_rank.svg"
    route_svg = output_dir / f"{output_prefix}_route_before_after.svg"
    dual_case_svg = output_dir / f"{output_prefix}_dual_case_comparison.svg"
    report_md = output_dir / f"{output_prefix}_route_analysis.md"

    write_metrics_csv(analyses, metrics_csv)
    plot_saving_ranking_svg(analyses, saving_svg, dataset_label)
    plot_route_before_after_svg(target_row, target_analysis, route_svg)
    plot_dual_case_comparison_svg(
        top_saving_row,
        top_saving_analysis,
        target_row,
        target_analysis,
        dual_case_svg,
        dataset_label,
    )
    write_markdown_report(analyses, target_row, target_analysis, report_md, dataset_label)

    print(f"Input: {input_csv}")
    print(f"Output dir: {output_dir}")
    print("Generated files:")
    print(f"  - {metrics_csv.name}")
    print(f"  - {saving_svg.name}")
    print(f"  - {route_svg.name}")
    print(f"  - {dual_case_svg.name}")
    print(f"  - {report_md.name}")
    print(f"Highest saving instance: {_instance_stem(top_saving_analysis.instance)}")
    print(f"Representative instance: {_instance_stem(target_analysis.instance)}")


if __name__ == "__main__":
    main()
