"""Initial solution builders for the refactored ALNS framework."""

from __future__ import annotations
from .solution import Solution
from .route import DroneTask, TruckRoute
from ..instance import InstanceManager
from ..evaluation.timing import TimingCalculator
from ..evaluation.energy import DroneEnergyModel
from ..utils.constants import (
    DEFAULT_DRONE_ID,
    DEFAULT_TRUCK_CAPACITY,
    DEFAULT_TRUCK_ID,
    DEPOT_ID,
)

import logging
import math
from collections import defaultdict
from typing import Dict, Iterable, List, Mapping, Sequence, Set, Tuple

logger = logging.getLogger(__name__)


logger = logging.getLogger(__name__)


def build_pseudo_solution(customers: Sequence[int] | None = None) -> Solution:
    """Create a trivial feasible solution used to exercise the framework."""
    """Create a trivial feasible solution used to exercise the framework."""
    if customers is None:
        customers = (1, 2)

    solution = Solution.empty()

    truck_nodes = [DEPOT_ID, *customers, DEPOT_ID]
    truck_route = TruckRoute(
        route_id=0,
        nodes=truck_nodes,
        capacity=DEFAULT_TRUCK_CAPACITY,
    )
    solution.add_truck_route(truck_route)

    if len(customers) >= 2:
        launch_node, delivery_customer = customers[:2]
        drone_task = DroneTask(
            task_id=1,
            drone_id=DEFAULT_DRONE_ID,
            launch_truck=DEFAULT_TRUCK_ID,
            launch_node=launch_node,
            customers=[delivery_customer],
            land_truck=DEFAULT_TRUCK_ID,
            retrieve_node=launch_node,
            payloads=[0.0, 0.0],
        )
        solution.add_drone_task(drone_task)

    return solution


def build_initial_solution(
    instance: InstanceManager,
    truck_forbidden_customers: Sequence[int] | None = None,
    allow_multiple_launch_per_node: bool = False,
) -> Solution:
    """Construct an initial solution with truck and drone routes.

    Truck tours are generated by a greedy k-nearest-neighbor heuristic. Drone
    tasks are then carved out sequentially by analysing consecutive truck nodes.
    If no drone task is created during the process, a fallback task is generated
    to guarantee that the initial solution contains at least one drone mission.

    Args:
        instance: Problem instance
        truck_forbidden_customers: Customers that cannot be visited by truck
    """

    forbidden_set = set(truck_forbidden_customers or [])

    # Generate time windows first to ensure truck routes respect them
    if not any(instance.customer_manager.time_window(c)[0] is not None
               for c in instance.customer_manager.customer_ids()):
        instance.generate_time_windows(strategy="class_based")

    solution = Solution.empty()

    truck_routes = _build_truck_routes(instance, time_limit=60.0)


    if forbidden_set:
        for route in truck_routes:
            original_nodes = list(route.nodes)
            # ，
            new_nodes = [original_nodes[0]]  # depot start
            for node in original_nodes[1:-1]:
                if node not in forbidden_set:
                    new_nodes.append(node)
            new_nodes.append(original_nodes[-1])  # depot end
            route._nodes = new_nodes
            route.nodes = new_nodes

    for route in truck_routes:
        solution.add_truck_route(route)

    # Validate forbidden customers can be served by drones. If any forbidden
    # customer exceeds drone capacity the initial solution is infeasible.
    if forbidden_set:
        drone_spec = instance.vehicle_specs.get("drone")
        drone_capacity = drone_spec.capacity if drone_spec is not None else float(
            "inf")
        demands = instance.customer_manager.demands()
        oversized = [c for c in forbidden_set if demands.get(
            c, 0.0) > drone_capacity]
        if oversized:
            details = ", ".join(f"{c}: {demands.get(c)}" for c in oversized)
            msg = (
                f"The following truck-forbidden customers exceed drone capacity ({drone_capacity}) and cannot be served: {details}"
            )
            logger.error(msg)
            raise ValueError(msg)

    # Store original nodes before modification
    original_truck_nodes = [list(route.nodes)
                            for route in solution.truck_routes]

    depot_drone_tasks = _construct_depot_drone_tasks(
        instance, original_truck_nodes, solution.truck_routes)
    route_id_to_idx = {route.id: idx for idx,
                       route in enumerate(solution.truck_routes)}
    reserved_retrievals: Set[Tuple[int, int]] = set()
    reserved_nodes: Dict[int, Set[int]] = defaultdict(set)
    drone_initial_availability: Dict[int, Tuple[int, int]] = {}

    for task in depot_drone_tasks:
        land_truck = task.land_truck
        if land_truck is None:
            continue

        anchor = (land_truck, task.retrieve_node)
        # Only reserve retrievals/nodes if the user disallows multiple launches per node
        if not allow_multiple_launch_per_node:
            reserved_retrievals.add(anchor)
            reserved_nodes[land_truck].add(task.retrieve_node)

        route_idx = route_id_to_idx.get(land_truck)
        if route_idx is None:
            continue
        nodes = solution.truck_routes[route_idx].nodes
        try:
            retrieve_pos = nodes.index(task.retrieve_node)
        except ValueError:
            continue
        drone_initial_availability[task.drone_id] = (
            solution.truck_routes[route_idx].id,
            retrieve_pos,
        )

    drone_tasks = _construct_cross_truck_drone_tasks(
        instance,
        solution.truck_routes,
        reserved_retrievals=reserved_retrievals,
        reserved_nodes=reserved_nodes,
        initial_drone_availability=drone_initial_availability,
    )
    for task in drone_tasks:
        solution.add_drone_task(task)

    # Add depot-launched drone tasks using original nodes (no conflicts expected now)
    for task in depot_drone_tasks:
        solution.add_drone_task(task)


    if forbidden_set:
        forbidden_drone_tasks = _construct_forbidden_customer_drone_tasks(
            instance,
            solution.truck_routes,
            forbidden_set,
            solution.drone_tasks,
        )
        for task in forbidden_drone_tasks:
            solution.add_drone_task(task)

    # Remove customers that are now fully served by drones
    for route in solution.truck_routes:
        _cleanup_truck_route(route, solution.drone_tasks)

    if not solution.drone_tasks and solution.truck_routes:
        fallback = _fallback_drone_task(instance, solution.truck_routes[0])
        if fallback is not None:
            solution.add_drone_task(fallback)

    demands = instance.customer_manager.demands()
    for route in solution.truck_routes:
        _update_truck_load(route, demands)
    return solution


def _construct_cross_truck_drone_tasks(
    instance: InstanceManager,
    truck_routes: Sequence[TruckRoute],
    *,
    reserved_retrievals: Set[Tuple[int, int]] | None = None,
    reserved_nodes: Dict[int, Set[int]] | None = None,
    initial_drone_availability: Dict[int, Tuple[int, int]] | None = None,
) -> List[DroneTask]:
    drone_spec = instance.vehicle_specs.get("drone")
    if drone_spec is None or drone_spec.number <= 0:
        return []
    if not truck_routes:
        return []

    demands = instance.customer_manager.demands()
    node_index = {node: idx for idx,
                  node in enumerate(instance.all_node_ids())}
    truck_matrix = instance.distance_matrix("truck")
    drone_matrix = instance.distance_matrix("drone")
    drone_time_matrix = instance.time_matrix("drone")
    energy_model = DroneEnergyModel()
    battery_capacity = instance.robust_config.drone_battery_capacity or float(
        "inf")

    route_nodes: List[List[int]] = [
        list(route.nodes) for route in truck_routes]
    assigned: List[List[bool]] = [
        [False] * len(nodes) for nodes in route_nodes]
    protected: List[List[bool]] = [
        [False] * len(nodes) for nodes in route_nodes]
    launch_used: List[List[bool]] = [
        [False] * len(nodes) for nodes in route_nodes]

    drone_ids = list(range(drone_spec.number)) or [0]
    reserved_retrievals = reserved_retrievals or set()
    reserved_nodes = reserved_nodes or {}
    initial_drone_availability = initial_drone_availability or {}
    task_id = 1
    tasks: List[DroneTask] = []

    # Track when each drone becomes available (completion time of last task)
    # Key: drone_id, Value: (retrieve_route_idx, retrieve_node_position)
    # This ensures a drone can only start a new task after completing the previous one
    drone_availability: Dict[int, Tuple[int, int]] = {
        drone_id: (-1, -1) for drone_id in drone_ids}

    route_id_to_idx = {route.id: idx for idx, route in enumerate(truck_routes)}
    for drone_id, (route_id, node_pos) in initial_drone_availability.items():
        route_idx = route_id_to_idx.get(route_id)
        if route_idx is None or drone_id not in drone_availability:
            continue
        drone_availability[drone_id] = (route_idx, node_pos)

    truck_cost_per_km = instance.vehicle_specs.get(
        "truck").unit_cost if instance.vehicle_specs.get("truck") else 1.0
    drone_cost_per_km = instance.vehicle_specs.get(
        "drone").unit_cost if instance.vehicle_specs.get("drone") else 1.0

    # Check if same-truck retrieval is enforced
    same_truck_only = instance.robust_config.same_truck_retrieval

    for route_id, nodes in reserved_nodes.items():
        route_idx = route_id_to_idx.get(route_id)
        if route_idx is None:
            continue
        for pos, node in enumerate(route_nodes[route_idx]):
            if node in nodes:
                protected[route_idx][pos] = True

    launch_queue: List[Tuple[int, int]] = []
    for route_idx, nodes in enumerate(route_nodes):
        for launch_idx in range(len(nodes) - 1):
            launch_queue.append((route_idx, launch_idx))

    for launch_route_idx, launch_idx in launch_queue:
        if assigned[launch_route_idx][launch_idx]:
            continue
        if launch_used[launch_route_idx][launch_idx]:
            continue
        launch_node = route_nodes[launch_route_idx][launch_idx]
        task_info = _build_task_from_launch(
            launch_route_idx,
            launch_idx,
            launch_node,
            route_nodes,
            assigned,
            protected,
            reserved_retrievals,
            truck_routes,
            drone_ids,
            drone_availability,
            demands,
            drone_spec.capacity,
            battery_capacity,
            node_index,
            truck_matrix,
            drone_matrix,
            drone_time_matrix,
            energy_model,
            truck_cost_per_km,
            drone_cost_per_km,
            same_truck_only,
            task_id,
        )
        if task_info is None:
            continue

        (
            task,
            drone_id,
            retrieve_route_idx,
            retrieve_node_pos,
            affected_positions,
        ) = task_info
        task.task_id = task_id
        tasks.append(task)
        launch_used[launch_route_idx][launch_idx] = True
        for pos in affected_positions:
            assigned[retrieve_route_idx][pos] = True
        protected[retrieve_route_idx][retrieve_node_pos] = True
        reserved_retrievals.add(
            (truck_routes[retrieve_route_idx].id,
             route_nodes[retrieve_route_idx][retrieve_node_pos])
        )
        drone_availability[drone_id] = (retrieve_route_idx, retrieve_node_pos)
        task_id += 1

    for route_idx, route in enumerate(truck_routes):
        nodes = route_nodes[route_idx]
        flags = assigned[route_idx]
        if len(nodes) <= 2:
            continue

        new_nodes: List[int] = [nodes[0]]
        for pos in range(1, len(nodes) - 1):
            if not flags[pos]:
                new_nodes.append(nodes[pos])
        new_nodes.append(nodes[-1])

        compact: List[int] = []
        for node in new_nodes:
            if not compact or compact[-1] != node:
                compact.append(node)
        route.nodes = compact

    return tasks


def _build_task_from_launch(
    launch_route_idx: int,
    launch_idx: int,
    launch_node: int,
    route_nodes: List[List[int]],
    assigned: List[List[bool]],
    protected: List[List[bool]],
    reserved_retrievals: Set[Tuple[int, int]],
    truck_routes: Sequence[TruckRoute],
    drone_ids: Sequence[int],
    drone_availability: Dict[int, Tuple[int, int]],
    demands: Mapping[int, float],
    drone_capacity: float,
    battery_capacity: float,
    node_index: Mapping[int, int],
    truck_matrix: Sequence[Sequence[float]],
    drone_matrix: Sequence[Sequence[float]],
    drone_time_matrix: Sequence[Sequence[float]],
    energy_model: DroneEnergyModel,
    truck_cost_per_km: float,
    drone_cost_per_km: float,
    same_truck_only: bool,
    task_id_start: int,
) -> Tuple[DroneTask, int, int, int, List[int]] | None:
    nodes = route_nodes[launch_route_idx]
    available_drone = _select_available_drone(
        drone_ids,
        drone_availability,
        launch_route_idx,
        launch_idx,
        same_truck_only,
    )
    if available_drone is None:
        return None

    best_customers: List[int] | None = None
    best_retrieve_idx: int | None = None
    best_delta = float("-inf")
    customers: List[int] = []
    payload = 0.0

    for cursor in range(max(launch_idx + 1, 1), len(nodes) - 1):
        if assigned[launch_route_idx][cursor]:
            break
        if protected[launch_route_idx][cursor]:
            break
        customer = nodes[cursor]
        if customer == launch_node:
            continue
        demand = demands.get(customer, 0.0)
        # if demand <= 0.0:
        #     break
        if payload + demand > drone_capacity:
            break

        retrieve_idx = cursor + 1
        if assigned[launch_route_idx][retrieve_idx]:
            break
        if protected[launch_route_idx][retrieve_idx]:
            break
        retrieve_node = nodes[retrieve_idx]
        anchor = (truck_routes[launch_route_idx].id, retrieve_node)
        if anchor in reserved_retrievals:
            break

        candidate_customers = customers + [customer]
        energy = _nominal_energy(
            launch=launch_node,
            customers=candidate_customers,
            retrieve=retrieve_node,
            demands=demands,
            energy_model=energy_model,
            time_matrix=drone_time_matrix,
            node_index=node_index,
        )
        if energy > battery_capacity:
            break

        payload += demand
        customers = candidate_customers

        truck_segment = nodes[launch_idx: retrieve_idx + 1]
        truck_removed = _path_distance(
            truck_matrix,
            truck_segment,
            node_index,
        )
        if not math.isfinite(truck_removed):
            break
        launch_idx_node = node_index.get(launch_node)
        retrieve_idx_node = node_index.get(retrieve_node)
        if launch_idx_node is None or retrieve_idx_node is None:
            break
        truck_added = truck_matrix[launch_idx_node][retrieve_idx_node]
        if truck_added == float("inf"):
            break

        drone_path = [launch_node, *customers, retrieve_node]
        drone_distance = _path_distance(drone_matrix, drone_path, node_index)
        if not math.isfinite(drone_distance):
            break

        delta_cost = (
            truck_cost_per_km * (truck_removed - truck_added)
            - drone_cost_per_km * drone_distance
        )
        if delta_cost <= 0.0:
            continue

        best_customers = list(customers)
        best_retrieve_idx = retrieve_idx
        best_delta = delta_cost

    if not best_customers or best_retrieve_idx is None:
        return None

    retrieve_node = nodes[best_retrieve_idx]
    payloads = _build_payloads(best_customers, demands)
    task = DroneTask(
        task_id=task_id_start,
        drone_id=available_drone,
        launch_truck=truck_routes[launch_route_idx].id,
        launch_node=launch_node,
        customers=best_customers,
        land_truck=truck_routes[launch_route_idx].id,
        retrieve_node=retrieve_node,
        payloads=payloads,
    )
    affected_positions = list(
        range(launch_idx + 1, best_retrieve_idx)
    )
    return task, available_drone, launch_route_idx, best_retrieve_idx, affected_positions


def _select_available_drone(
    drone_ids: Sequence[int],
    availability: Mapping[int, Tuple[int, int]],
    launch_route_idx: int,
    launch_idx: int,
    same_truck_only: bool,
) -> int | None:
    for drone_id in drone_ids:
        prev_route_idx, prev_pos = availability.get(drone_id, (-1, -1))
        if prev_route_idx == -1:
            return drone_id
        if prev_route_idx == launch_route_idx and prev_pos < launch_idx:
            return drone_id
        if not same_truck_only and prev_route_idx != launch_route_idx:
            return drone_id
    return None


def _build_truck_routes(instance: InstanceManager, time_limit: float | None = None) -> List[TruckRoute]:
    truck_spec = instance.vehicle_specs.get("truck")
    capacity = truck_spec.capacity if truck_spec is not None else DEFAULT_TRUCK_CAPACITY

    return _build_k_greedy_routes(instance)


def _build_k_greedy_routes(instance: InstanceManager) -> List[TruckRoute]:
    customers = set(instance.customer_manager.customer_ids())
    depot_start = instance.customer_manager.depot_start
    depot_end = instance.customer_manager.depot_end or depot_start
    customers.discard(depot_start)
    customers.discard(depot_end)

    node_ids = instance.all_node_ids()
    node_index = {node: idx for idx, node in enumerate(node_ids)}
    distance_matrix = instance.distance_matrix("truck")
    time_matrix = instance.time_matrix("truck")

    truck_spec = instance.vehicle_specs.get("truck")
    num_trucks = truck_spec.number if truck_spec is not None else 1
    capacity = truck_spec.capacity if truck_spec is not None else DEFAULT_TRUCK_CAPACITY

    clusters = [list() for _ in range(num_trucks)]
    sorted_customers = sorted(customers)
    for idx, customer in enumerate(sorted_customers):
        clusters[idx % num_trucks].append(customer)

    routes: List[TruckRoute] = []
    route_id = 0
    for cluster in clusters:
        if not cluster:
            routes.append(TruckRoute(route_id=route_id, nodes=[
                          depot_start, depot_end], capacity=capacity))
            route_id += 1
            continue

        remaining = set(cluster)
        current = depot_start
        route_nodes = [depot_start]
        current_time = 0.0  # Start from depot at time 0

        while remaining:
            next_customer = _next_feasible_customer(
                current, remaining, node_index, distance_matrix, time_matrix,
                instance, current_time)
            if next_customer is None:
                break
            route_nodes.append(next_customer)
            remaining.remove(next_customer)
            # Update current time using time matrix
            travel_time = time_matrix[node_index[current]
                                      ][node_index[next_customer]]
            current_time += travel_time
            current = next_customer

        route_nodes.append(depot_end)
        routes.append(TruckRoute(route_id=route_id,
                      nodes=route_nodes, capacity=capacity))
        route_id += 1

    return routes


def _fallback_drone_task(instance: InstanceManager, truck_route: TruckRoute) -> DroneTask | None:
    nodes = list(truck_route.nodes)
    if len(nodes) < 3:
        return None

    drone_spec = instance.vehicle_specs.get("drone")
    if drone_spec is None or drone_spec.number <= 0:
        return None

    demands = instance.customer_manager.demands()
    capacity = drone_spec.capacity

    node_index = {node: idx for idx,
                  node in enumerate(instance.all_node_ids())}
    time_matrix = instance.time_matrix("drone")
    energy_model = DroneEnergyModel()
    battery_capacity = instance.robust_config.drone_battery_capacity

    for idx in range(1, len(nodes) - 1):
        candidate = nodes[idx]
        payload = demands.get(candidate, 0.0)
        if payload > capacity:  # or payload <= 0.0:
            continue

        launch_node = nodes[idx - 1]
        retrieve_node = nodes[idx + 1]
        energy = _nominal_energy(
            launch=launch_node,
            customers=[candidate],
            retrieve=retrieve_node,
            demands=demands,
            energy_model=energy_model,
            time_matrix=time_matrix,
            node_index=node_index,
        )
        if energy > battery_capacity:
            continue

        payloads = _build_payloads([candidate], demands)
        task = DroneTask(
            task_id=1,
            drone_id=0,
            launch_truck=truck_route.id,
            launch_node=launch_node,
            customers=[candidate],
            land_truck=truck_route.id,
            retrieve_node=retrieve_node,
            payloads=payloads,
        )
        truck_route.nodes = nodes[:idx] + nodes[idx + 1:]
        return task

    return None


def _build_payloads(customers: Sequence[int], demands: Mapping[int, float]) -> List[float]:
    payloads: List[float] = []
    current = sum(demands.get(customer, 0.0) for customer in customers)
    payloads.append(current)
    for customer in customers:
        current -= demands.get(customer, 0.0)
        payloads.append(max(current, 0.0))
    return payloads


def _nominal_energy(
    *,
    launch: int,
    customers: Sequence[int],
    retrieve: int,
    demands: Mapping[int, float],
    energy_model: DroneEnergyModel,
    time_matrix: Sequence[Sequence[float]],
    node_index: Mapping[int, int],
) -> float:
    if not customers:
        return 0.0

    nodes = [launch, *customers, retrieve]
    payloads = _build_payloads(customers, demands)
    energy = 0.0

    for payload, start, end in zip(payloads, nodes, nodes[1:]):
        i = node_index.get(start)
        j = node_index.get(end)
        if i is None or j is None:
            return float("inf")
        travel_time = time_matrix[i][j]
        if travel_time == float("inf"):
            return float("inf")
        energy += energy_model.energy_kwh(payload, travel_time)

    return energy


def _next_feasible_customer(
    origin: int,
    candidates: Set[int],
    node_index: Mapping[int, int],
    distance_matrix: Sequence[Sequence[float]],
    time_matrix: Sequence[Sequence[float]],
    instance: InstanceManager,
    current_time: float,
) -> int | None:
    """Select the nearest customer that can be visited within time window constraints."""
    """Select the nearest customer that can be visited within time window constraints."""
    shortest = float("inf")
    best = None
    i = node_index.get(origin)
    if i is None:
        return None

    for candidate in candidates:
        j = node_index.get(candidate)
        if j is None:
            continue
        distance = distance_matrix[i][j]
        if distance == float("inf"):
            continue

        # Use time matrix for arrival time calculation
        travel_time = time_matrix[i][j]
        arrival_time = current_time + travel_time
        time_window_start, time_window_end = instance.customer_manager.time_window(
            candidate)

        # If time window is not set, assume it's feasible
        if time_window_start is None or time_window_end is None:
            if distance < shortest:
                shortest = distance
                best = candidate
            continue

        # Check if arrival time is within time window (with some tolerance)
        # Allow arrival slightly before start (waiting) or exactly at end
        if arrival_time <= time_window_end + 0.1:  # Small tolerance
            if distance < shortest:
                shortest = distance
                best = candidate

    return best


def _update_truck_load(truck_route: TruckRoute, demands: Mapping[int, float]) -> None:
    load = sum(demands.get(customer, 0.0)
               for customer in truck_route.customers())
    truck_route.current_load = load


def _cleanup_truck_route(truck_route: TruckRoute, drone_tasks: Sequence[DroneTask]) -> None:
    if not drone_tasks:
        return

    served_by_drone: Set[int] = set()
    sync_nodes: Set[int] = set()
    for task in drone_tasks:
        served_by_drone.update(task.customers())
        sync_nodes.add(task.launch_node)
        sync_nodes.add(task.retrieve_node)

    if not served_by_drone:
        return

    new_nodes: List[int] = []
    for node in truck_route.nodes:
        if node in served_by_drone and node not in sync_nodes:
            continue
        new_nodes.append(node)

    if new_nodes != truck_route.nodes and len(new_nodes) >= 2:
        truck_route.nodes = new_nodes


def _customers_after_launch(
    nodes: Sequence[int],
    launch_index: int,
    candidates: Set[int],
) -> Set[int]:
    subset: Set[int] = set()
    for node in nodes[launch_index + 1:]:
        if node in candidates:
            subset.add(node)
    return subset


def _next_truck_node_after(nodes: Sequence[int], customer: int) -> int | None:
    try:
        idx = nodes.index(customer)
    except ValueError:
        return nodes[-1] if nodes else None

    if idx + 1 < len(nodes):
        return nodes[idx + 1]
    return nodes[-1] if nodes else None


def _construct_forbidden_customer_drone_tasks(
    instance: InstanceManager,
    truck_routes: Sequence[TruckRoute],
    forbidden_customers: Set[int],
    existing_drone_tasks: Sequence[DroneTask],
) -> List[DroneTask]:
    """。

    depot，。

    Args:
        instance: 
        truck_routes: 
        forbidden_customers: 
        existing_drone_tasks: （）

    Returns:
        
    """
    if not forbidden_customers or not truck_routes:
        return []

    drone_spec = instance.vehicle_specs.get("drone")
    if drone_spec is None or drone_spec.number <= 0:
        return []


    served_by_drone: Set[int] = set()
    for task in existing_drone_tasks:
        served_by_drone.update(task.customers())

    unserved_forbidden = forbidden_customers - served_by_drone
    if not unserved_forbidden:
        return []

    demands = instance.customer_manager.demands()
    depot_start = instance.customer_manager.depot_start
    depot_end = instance.customer_manager.depot_end or depot_start
    node_index = {node: idx for idx,
                  node in enumerate(instance.all_node_ids())}
    drone_matrix = instance.distance_matrix("drone")
    drone_time_matrix = instance.time_matrix("drone")
    energy_model = DroneEnergyModel()
    battery_capacity = instance.robust_config.drone_battery_capacity or float(
        "inf")

    tasks: List[DroneTask] = []
    task_id = 2000  # ID
    drone_ids = list(range(drone_spec.number)) or [0]
    next_drone_idx = 0


    for customer in sorted(unserved_forbidden):
        if next_drone_idx >= len(drone_ids):

            next_drone_idx = 0

        demand = demands.get(customer, 0.0)
        if demand > drone_spec.capacity:
            logger.warning(
                f"Forbidden customer {customer} demand {demand} exceeds drone capacity {drone_spec.capacity}")
            continue

        # （）
        best_retrieve_node: int | None = None
        best_retrieve_route: TruckRoute | None = None
        best_energy = float("inf")

        for route in truck_routes:

            for node in route.nodes:
                if node == depot_start or node == depot_end:
                    # depot
                    pass
                if node in forbidden_customers and node != depot_start and node != depot_end:
                    # （depot）
                    continue

                # ：depot -> customer -> node
                energy = _nominal_energy(
                    launch=depot_start,
                    customers=[customer],
                    retrieve=node,
                    demands=demands,
                    energy_model=energy_model,
                    time_matrix=drone_time_matrix,
                    node_index=node_index,
                )

                if energy < best_energy and energy <= battery_capacity:
                    best_energy = energy
                    best_retrieve_node = node
                    best_retrieve_route = route

        if best_retrieve_node is None or best_retrieve_route is None:
            logger.warning(
                f"Could not find valid drone task for forbidden customer {customer}")
            continue

        payloads = _build_payloads([customer], demands)
        task = DroneTask(
            task_id=task_id,
            drone_id=drone_ids[next_drone_idx],
            launch_truck=None,  # depot
            launch_node=depot_start,
            customers=[customer],
            land_truck=best_retrieve_route.id,
            retrieve_node=best_retrieve_node,
            payloads=payloads,
        )
        tasks.append(task)
        task_id += 1
        next_drone_idx += 1
        logger.info(
            f"Created drone task for forbidden customer {customer}: depot -> {customer} -> {best_retrieve_node}")

    return tasks


def _construct_depot_drone_tasks(
    instance: InstanceManager,
    original_truck_nodes: Sequence[Sequence[int]],
    truck_routes: Sequence[TruckRoute],
) -> List[DroneTask]:
    """Construct drone tasks that launch from depot and retrieve at truck routes."""
    """Construct drone tasks that launch from depot and retrieve at truck routes."""
    drone_spec = instance.vehicle_specs.get("drone")
    if drone_spec is None or drone_spec.number <= 0:
        return []
    if not truck_routes:
        return []

    demands = instance.customer_manager.demands()
    depot_start = instance.customer_manager.depot_start
    depot_end = instance.customer_manager.depot_end or depot_start
    node_index = {node: idx for idx,
                  node in enumerate(instance.all_node_ids())}
    truck_matrix = instance.distance_matrix("truck")
    drone_matrix = instance.distance_matrix("drone")
    drone_time_matrix = instance.time_matrix("drone")
    energy_model = DroneEnergyModel()
    battery_capacity = instance.robust_config.drone_battery_capacity or float(
        "inf")

    tasks: List[DroneTask] = []
    drone_ids = list(range(drone_spec.number)) or [0]
    available_depot_drones = list(drone_ids)
    next_depot_drone_idx = 0
    task_id = 1000  # High task_id to avoid conflict
    truck_cost_per_km = instance.vehicle_specs.get(
        "truck").unit_cost if instance.vehicle_specs.get("truck") else 1.0
    drone_cost_per_km = instance.vehicle_specs.get(
        "drone").unit_cost if instance.vehicle_specs.get("drone") else 1.0
    max_customers_per_task = 3

    candidates: List[Tuple[float, TruckRoute, int, List[int]]] = []

    for route_idx, route in enumerate(truck_routes):
        original_nodes = original_truck_nodes[route_idx]
        if len(original_nodes) <= 2:
            continue

        for start in range(1, len(original_nodes) - 1):
            prev_node = original_nodes[start - 1]
            customers: List[int] = []
            payload = 0.0

            for end in range(start, len(original_nodes) - 1):
                customer = original_nodes[end]
                if customer in (depot_start, depot_end):
                    break
                demand = demands.get(customer, 0.0)
                # if demand <= 0.0:
                #     break
                if payload + demand > drone_spec.capacity:
                    break

                customers.append(customer)
                payload += demand
                if len(customers) > max_customers_per_task:
                    break

                retrieve_node = original_nodes[end + 1]
                if retrieve_node not in route.nodes:
                    continue

                energy = _nominal_energy(
                    launch=depot_start,
                    customers=customers,
                    retrieve=retrieve_node,
                    demands=demands,
                    energy_model=energy_model,
                    time_matrix=drone_time_matrix,
                    node_index=node_index,
                )
                if energy > battery_capacity:
                    break

                truck_path = [prev_node, *customers, retrieve_node]
                truck_removed = _path_distance(
                    truck_matrix, truck_path, node_index)
                if truck_removed == float("inf"):
                    continue
                pre_idx = node_index.get(prev_node)
                ret_idx = node_index.get(retrieve_node)
                if pre_idx is None or ret_idx is None:
                    continue
                truck_added = truck_matrix[pre_idx][ret_idx]
                if truck_added == float("inf"):
                    continue

                drone_path = [depot_start, *customers, retrieve_node]
                drone_distance = _path_distance(
                    drone_matrix, drone_path, node_index)
                if drone_distance == float("inf"):
                    continue

                delta_cost = (
                    truck_cost_per_km * (truck_removed - truck_added)
                    - drone_cost_per_km * drone_distance
                )
                if delta_cost <= 0.0:
                    continue

                candidates.append((
                    delta_cost,
                    route,
                    retrieve_node,
                    list(customers),
                ))

    candidates.sort(key=lambda entry: entry[0], reverse=True)
    used_customers: Set[int] = set()
    used_retrievals: Set[Tuple[int, int]] = set()

    for gain, route, retrieve_node, customers in candidates:
        if next_depot_drone_idx >= len(available_depot_drones):
            break

        anchor = (route.id, retrieve_node)
        if anchor in used_retrievals:
            continue
        if any(customer in used_customers for customer in customers):
            continue

        depot_drone_id = available_depot_drones[next_depot_drone_idx]
        next_depot_drone_idx += 1
        payloads = _build_payloads(customers, demands)
        task = DroneTask(
            task_id=task_id,
            drone_id=depot_drone_id,
            launch_truck=None,
            launch_node=depot_start,
            customers=list(customers),
            land_truck=route.id,
            retrieve_node=retrieve_node,
            payloads=payloads,
        )
        tasks.append(task)
        task_id += 1
        used_retrievals.add(anchor)
        used_customers.update(customers)

    return tasks


def _path_distance(
    matrix: Sequence[Sequence[float]],
    nodes: Sequence[int],
    node_index: Mapping[int, int],
) -> float:
    distance = 0.0
    for start, end in zip(nodes, nodes[1:]):
        i = node_index.get(start)
        j = node_index.get(end)
        if i is None or j is None:
            return float("inf")
        seg = matrix[i][j]
        if seg == float("inf"):
            return float("inf")
        distance += seg
    return distance


# =============================================================================
# Two-Phase Heuristic Initial Solution (Algorithm 2 from paper)
# =============================================================================

def build_two_phase_initial_solution(
    instance: InstanceManager,
    truck_forbidden_customers: Sequence[int] | None = None,
    allow_multiple_launch_per_node: bool = False,
    energy_model: DroneEnergyModel | None = None,
) -> Solution:
    """Construct initial solution using two-phase heuristic (Algorithm 2).

    This algorithm follows the paper's approach:
    1. Phase 1: Generate truck-only routes using Nearest Neighbor heuristic
       respecting capacity and time window constraints
    2. Phase 2: Convert to MFS-VRPD solution by assigning customers to drones
       (Algorithm 2 / Appendix B.1)

    Args:
        instance: Problem instance
        truck_forbidden_customers: Customers that cannot be visited by truck

    Returns:
        Initial solution with truck routes and drone tasks
    """
    forbidden_set = set(truck_forbidden_customers or [])

    # Ensure time windows are generated
    if not any(instance.customer_manager.time_window(c)[0] is not None
               for c in instance.customer_manager.customer_ids()):
        instance.generate_time_windows(strategy="class_based")

    solution = Solution.empty()

    # Phase 1: Build truck-only routes using Nearest Neighbor
    logger.info(
        "Phase 1: Building truck routes using Nearest Neighbor heuristic")
    truck_routes = _build_nearest_neighbor_routes(instance)

    # Check for customers not served by trucks (due to truck limit)
    all_customers = set(instance.customer_manager.customer_ids())
    depot_start = instance.customer_manager.depot_start
    depot_end = instance.customer_manager.depot_end or depot_start
    all_customers.discard(depot_start)
    all_customers.discard(depot_end)

    truck_served = set()
    for route in truck_routes:
        for node in route.nodes[1:-1]:  # Exclude depots
            truck_served.add(node)

    # Customers not served by trucks must be served by drones
    unserved_by_truck = all_customers - truck_served
    if unserved_by_truck:
        logger.info(
            f"Customers {unserved_by_truck} not served by trucks (vehicle limit), will be assigned to drones")
        forbidden_set.update(unserved_by_truck)

        # Validate that customers that must be assigned to drones are drone-serviceable
        # If any customer's demand exceeds the drone capacity, the problem is infeasible
        # under the current truck limit and drone specs. Raise a clear error instead
        # of silently producing an infeasible initial solution.
        drone_spec = instance.vehicle_specs.get("drone")
        drone_capacity = drone_spec.capacity if drone_spec is not None else float(
            "inf")
        demands = instance.customer_manager.demands()
        oversized = [c for c in unserved_by_truck if demands.get(
            c, 0.0) > drone_capacity]
        if oversized:
            # Format message listing all oversized customers and their demands
            details = ", ".join(f"{c}: {demands.get(c)}" for c in oversized)
            msg = (
                f"The following customers will need to be served by drones because "
                f"all trucks are at capacity, but their demand exceeds the drone "
                f"capacity ({drone_capacity}): {details}."
            )
            logger.error(msg)
            raise ValueError(msg)

    # Remove forbidden customers from truck routes
    if forbidden_set:
        for route in truck_routes:
            original_nodes = list(route.nodes)
            new_nodes = [original_nodes[0]]  # depot start
            for node in original_nodes[1:-1]:
                if node not in forbidden_set:
                    new_nodes.append(node)
            new_nodes.append(original_nodes[-1])  # depot end
            route.nodes = new_nodes

    # Filter out empty routes (only depot start and end)
    non_empty_routes = [r for r in truck_routes if len(r.nodes) > 2]
    if not non_empty_routes:
        # Keep at least one route if all are empty
        non_empty_routes = truck_routes[:1] if truck_routes else []

    for route in non_empty_routes:
        solution.add_truck_route(route)

    # Phase 2: Convert to MFS-VRPD by assigning customers to drones
    logger.info("Phase 2: Converting to MFS-VRPD solution (Algorithm 2)")
    drone_tasks = _convert_to_mfs_vrpd(
        instance, solution.truck_routes, forbidden_set,
        allow_multiple_launch_per_node=allow_multiple_launch_per_node,
        energy_model=energy_model,
    )

    for task in drone_tasks:
        solution.add_drone_task(task)

    # Clean up truck routes (remove drone-served customers)
    for route in solution.truck_routes:
        _cleanup_truck_route(route, solution.drone_tasks)

    # Filter empty routes again after cleanup (some routes may become empty)
    non_empty_after_cleanup = [
        r for r in solution.truck_routes if len(r.nodes) > 2]
    if non_empty_after_cleanup:
        solution._truck_routes = non_empty_after_cleanup
    else:
        # Keep at least one route
        solution._truck_routes = solution.truck_routes[:1] if solution.truck_routes else [
        ]

    # For small toy instances, keep a drone task so operator tests exercise
    # drone logic. For large benchmark instances, do not force a drone task:
    # a feasible truck-only backbone is a better ALNS starting point than an
    # artificial sortie that can violate tight time windows.
    if (
        not solution.drone_tasks
        and solution.truck_routes
        and len(all_customers) < 40
    ):
        fallback = _fallback_drone_task(instance, solution.truck_routes[0])
        if fallback is not None:
            solution.add_drone_task(fallback)

    # Update truck loads
    demands = instance.customer_manager.demands()
    for route in solution.truck_routes:
        _update_truck_load(route, demands)

    return solution


def _build_nearest_neighbor_routes(instance: InstanceManager) -> List[TruckRoute]:
    """Phase 1: Build truck routes using Nearest Neighbor heuristic.

    Process:
    1. Truck starts from depot
    2. Repeatedly find and visit the nearest unserved customer
    3. When adding next customer would violate capacity or time window,
       current truck stops and a new truck is dispatched
    4. Continue until all customers are served or max trucks reached

    Note: Respects the truck number limit from instance configuration.
    If more trucks would be needed, remaining customers must be served by drones.
    """
    customers = set(instance.customer_manager.customer_ids())
    depot_start = instance.customer_manager.depot_start
    depot_end = instance.customer_manager.depot_end or depot_start
    customers.discard(depot_start)
    customers.discard(depot_end)

    if not customers:
        return []

    node_ids = instance.all_node_ids()
    node_index = {node: idx for idx, node in enumerate(node_ids)}
    distance_matrix = instance.distance_matrix("truck")
    time_matrix = instance.time_matrix("truck")

    truck_spec = instance.vehicle_specs.get("truck")
    capacity = truck_spec.capacity if truck_spec is not None else DEFAULT_TRUCK_CAPACITY
    max_trucks = truck_spec.number if truck_spec is not None else 2  # Respect truck limit

    demands = instance.customer_manager.demands()
    # Prefer customers with demand > drone_capacity when constructing
    # truck routes. This reduces the chance of creating infeasible cases
    # where a heavy customer is left for a drone but exceeds drone capacity.
    drone_spec = instance.vehicle_specs.get("drone")
    drone_capacity = drone_spec.capacity if drone_spec is not None else float(
        "inf")
    heavy_customers = {c for c, d in demands.items() if d > drone_capacity}

    if len(customers) >= 40:
        return _build_deadline_balanced_routes(
            customers=customers,
            depot_start=depot_start,
            depot_end=depot_end,
            max_trucks=max_trucks,
            capacity=capacity,
            demands=demands,
            node_index=node_index,
            time_matrix=time_matrix,
            instance=instance,
        )

    routes: List[TruckRoute] = []
    route_id = 0
    remaining = set(customers)

    while remaining and route_id < max_trucks:
        # Start new truck route from depot
        route_nodes = [depot_start]
        current_node = depot_start
        current_time = 0.0
        current_load = 0.0

        while remaining:
            # Try to place heavy customers first (those impossible for drones).
            # Among heavy customers, prioritize the tightest hard deadline;
            # nearest-heavy greedily leaves early-deadline heavy customers
            # stranded on larger 50-customer instances.
            next_customer = None
            heavy_candidates = heavy_customers & remaining
            if heavy_candidates:
                next_customer = _find_earliest_deadline_feasible_nn(
                    current_node=current_node,
                    candidates=heavy_candidates,
                    node_index=node_index,
                    distance_matrix=distance_matrix,
                    time_matrix=time_matrix,
                    instance=instance,
                    current_time=current_time,
                    current_load=current_load,
                    capacity=capacity,
                    demands=demands,
                    depot_end=depot_end,
                )

            if next_customer is None:
                # Find nearest feasible customer (fallback to general NN)
                next_customer = _find_nearest_feasible_nn(
                    current_node=current_node,
                    candidates=remaining,
                    node_index=node_index,
                    distance_matrix=distance_matrix,
                    time_matrix=time_matrix,
                    instance=instance,
                    current_time=current_time,
                    current_load=current_load,
                    capacity=capacity,
                    demands=demands,
                    depot_end=depot_end,
                )

            if next_customer is None:
                # No feasible customer, end current route
                break

            # Add customer to route
            route_nodes.append(next_customer)
            remaining.remove(next_customer)
            # If we just placed a heavy customer, remove from heavy set
            if next_customer in heavy_customers:
                heavy_customers.discard(next_customer)

            # Update state
            travel_time = time_matrix[node_index[current_node]
                                      ][node_index[next_customer]]
            arrival_time = current_time + travel_time

            # Wait if arriving before time window opens
            tw_start, tw_end = instance.customer_manager.time_window(
                next_customer)
            if tw_start is not None and arrival_time < tw_start:
                current_time = tw_start  # Wait until window opens
            else:
                current_time = arrival_time

            current_load += demands.get(next_customer, 0.0)
            current_node = next_customer

        # Close route at depot
        route_nodes.append(depot_end)
        routes.append(TruckRoute(route_id=route_id,
                      nodes=route_nodes, capacity=capacity))
        route_id += 1

    return routes


def _build_deadline_balanced_routes(
    *,
    customers: Set[int],
    depot_start: int,
    depot_end: int,
    max_trucks: int,
    capacity: float,
    demands: Mapping[int, float],
    node_index: Mapping[int, int],
    time_matrix: Sequence[Sequence[float]],
    instance: InstanceManager,
) -> List[TruckRoute]:
    """Build large-instance truck routes by assigning earliest deadlines first."""
    """Build large-instance truck routes by assigning earliest deadlines first."""
    deadline_buffer = 0.05
    ordered_customers = sorted(
        customers,
        key=lambda customer: (
            instance.customer_manager.time_window(customer)[1]
            if instance.customer_manager.time_window(customer)[1] is not None
            else float("inf"),
            instance.customer_manager.time_window(customer)[0]
            if instance.customer_manager.time_window(customer)[0] is not None
            else 0.0,
            customer,
        ),
    )

    route_nodes: List[List[int]] = [[depot_start] for _ in range(max_trucks)]
    route_times = [0.0 for _ in range(max_trucks)]
    route_loads = [0.0 for _ in range(max_trucks)]

    for customer in ordered_customers:
        tw_start, tw_end = instance.customer_manager.time_window(customer)
        demand = demands.get(customer, 0.0)
        options = []
        for route_idx in range(max_trucks):
            if route_loads[route_idx] + demand > capacity:
                continue
            current = route_nodes[route_idx][-1]
            i = node_index.get(current)
            j = node_index.get(customer)
            if i is None or j is None:
                continue
            travel_time = time_matrix[i][j]
            if travel_time == float("inf"):
                continue
            arrival = route_times[route_idx] + travel_time
            service_time = (
                tw_start if tw_start is not None and arrival < tw_start
                else arrival
            )
            hard_violation = (
                tw_end is not None and service_time > tw_end - deadline_buffer
            )
            options.append((hard_violation, service_time, travel_time, route_idx))

        if not options:
            # Capacity should make this rare; keep deterministic behavior.
            route_idx = min(range(max_trucks), key=lambda idx: route_loads[idx])
            current = route_nodes[route_idx][-1]
            travel_time = time_matrix[node_index[current]][node_index[customer]]
            arrival = route_times[route_idx] + travel_time
            service_time = (
                tw_start if tw_start is not None and arrival < tw_start
                else arrival
            )
        else:
            _, service_time, _, route_idx = min(options)

        route_nodes[route_idx].append(customer)
        route_times[route_idx] = service_time
        route_loads[route_idx] += demand

    routes: List[TruckRoute] = []
    for route_id, nodes in enumerate(route_nodes):
        if nodes[-1] != depot_end:
            nodes.append(depot_end)
        routes.append(TruckRoute(route_id=route_id, nodes=nodes, capacity=capacity))
    return routes


def _find_earliest_deadline_feasible_nn(
    current_node: int,
    candidates: Set[int],
    node_index: Mapping[int, int],
    distance_matrix: Sequence[Sequence[float]],
    time_matrix: Sequence[Sequence[float]],
    instance: InstanceManager,
    current_time: float,
    current_load: float,
    capacity: float,
    demands: Mapping[int, float],
    depot_end: int,
) -> int | None:
    """Find feasible customer with earliest hard deadline, then shortest distance."""
    """Find feasible customer with earliest hard deadline, then shortest distance."""
    best_key = (float("inf"), float("inf"))
    best_customer = None

    i = node_index.get(current_node)
    if i is None:
        return None

    depot_idx = node_index.get(depot_end)

    for customer in candidates:
        j = node_index.get(customer)
        if j is None:
            continue

        distance = distance_matrix[i][j]
        if distance == float("inf"):
            continue

        demand = demands.get(customer, 0.0)
        if current_load + demand > capacity:
            continue

        travel_time = time_matrix[i][j]
        arrival_time = current_time + travel_time

        _, tw_end = instance.customer_manager.time_window(customer)
        if tw_end is not None and arrival_time > tw_end:
            continue

        if depot_idx is not None and time_matrix[j][depot_idx] == float("inf"):
            continue

        key = (tw_end if tw_end is not None else float("inf"), distance)
        if key < best_key:
            best_key = key
            best_customer = customer

    return best_customer


def _find_nearest_feasible_nn(
    current_node: int,
    candidates: Set[int],
    node_index: Mapping[int, int],
    distance_matrix: Sequence[Sequence[float]],
    time_matrix: Sequence[Sequence[float]],
    instance: InstanceManager,
    current_time: float,
    current_load: float,
    capacity: float,
    demands: Mapping[int, float],
    depot_end: int,
) -> int | None:
    """Find nearest customer satisfying capacity and time window constraints."""
    """Find nearest customer satisfying capacity and time window constraints."""
    shortest_dist = float("inf")
    best_customer = None

    i = node_index.get(current_node)
    if i is None:
        return None

    depot_idx = node_index.get(depot_end)

    for customer in candidates:
        j = node_index.get(customer)
        if j is None:
            continue

        distance = distance_matrix[i][j]
        if distance == float("inf"):
            continue

        # Check capacity constraint
        demand = demands.get(customer, 0.0)
        if current_load + demand > capacity:
            continue

        # Check time window constraint
        travel_time = time_matrix[i][j]
        arrival_time = current_time + travel_time

        tw_start, tw_end = instance.customer_manager.time_window(customer)
        if tw_end is not None and arrival_time > tw_end:
            # Cannot arrive before deadline
            continue

        # Check if we can return to depot after visiting this customer
        if depot_idx is not None:
            return_time_to_depot = time_matrix[j][depot_idx]
            service_time = tw_start if tw_start is not None and arrival_time < tw_start else arrival_time
            # Add some buffer for service (simplified)
            if return_time_to_depot == float("inf"):
                continue

        if distance < shortest_dist:
            shortest_dist = distance
            best_customer = customer

    return best_customer


def _convert_to_mfs_vrpd(
    instance: InstanceManager,
    truck_routes: Sequence[TruckRoute],
    forbidden_customers: Set[int],
    allow_multiple_launch_per_node: bool = False,
    energy_model: DroneEnergyModel | None = None,
) -> List[DroneTask]:
    """Phase 2: Convert truck-only solution to MFS-VRPD (Algorithm 2).

    Process (Appendix B.1):
    1. Initialize: Identify drone-serviceable customers C_D
    2. For each drone, plan sub-routes:
       a. Select launch node on truck route
       b. Select nearest customer from C_D (nearest neighbor)
       c. Remove customer from truck route, update state
       d. Find nearest truck node as retrieve point
       e. Try multi-visit extension until energy/capacity exhausted
       f. Start new sub-route or move to next drone
    """
    drone_spec = instance.vehicle_specs.get("drone")
    if drone_spec is None or drone_spec.number <= 0:
        return []

    if not truck_routes:
        return []

    # Initialize problem data
    demands = instance.customer_manager.demands()
    node_index = {node: idx for idx,
                  node in enumerate(instance.all_node_ids())}
    truck_matrix = instance.distance_matrix("truck")
    drone_matrix = instance.distance_matrix("drone")
    drone_time_matrix = instance.time_matrix("drone")
    truck_time_matrix = instance.time_matrix("truck")
    energy_model = energy_model or DroneEnergyModel()

    battery_capacity = instance.robust_config.drone_battery_capacity
    drone_capacity = drone_spec.capacity
    deviation_rate = instance.robust_config.energy_deviation_rate
    uncertainty_budget = instance.robust_config.energy_uncertainty_budget

    # Identify drone-serviceable customers (C_D)
    # C_D should only contain customers NOT already on truck routes
    # (i.e., forbidden customers that couldn't be placed on truck routes)
    # Customers on truck routes are served by trucks, not drones
    depot_start = instance.customer_manager.depot_start
    depot_end = instance.customer_manager.depot_end or depot_start

    # Collect all customers already on truck routes (served by trucks)
    truck_served: Set[int] = set()
    for route in truck_routes:
        for node in route.nodes[1:-1]:  # Exclude depots
            if node != depot_start and node != depot_end:
                truck_served.add(node)

    # C_D = forbidden customers that are NOT on truck routes
    # These must be served by drones
    c_d: Set[int] = forbidden_customers - truck_served

    if not c_d:
        return []

    # Track route state (which nodes are still on truck route)
    route_nodes: List[List[int]] = [
        list(route.nodes) for route in truck_routes]
    assigned_to_drone: Set[int] = set()

    tasks: List[DroneTask] = []
    task_id = 1
    drone_ids = list(range(drone_spec.number))

    # Track drone availability: (last_retrieve_route_idx, last_retrieve_pos)
    drone_availability: Dict[int, Tuple[int, int]] = {
        d: (-1, -1) for d in drone_ids}

    same_truck_only = instance.robust_config.same_truck_retrieval

    while c_d:
        progress = False
        for drone_id in drone_ids:
            if not c_d:
                break

            task = _build_drone_subroute_nn(
                drone_id=drone_id,
                route_nodes=route_nodes,
                truck_routes=truck_routes,
                c_d=c_d,
                assigned_to_drone=assigned_to_drone,
                drone_availability=drone_availability,
                demands=demands,
                node_index=node_index,
                drone_matrix=drone_matrix,
                drone_time_matrix=drone_time_matrix,
                truck_time_matrix=truck_time_matrix,
                energy_model=energy_model,
                battery_capacity=battery_capacity,
                drone_capacity=drone_capacity,
                deviation_rate=deviation_rate,
                uncertainty_budget=uncertainty_budget,
                instance=instance,
                same_truck_only=same_truck_only,
                task_id=task_id,
            )

            if task is None:
                continue

            tasks.append(task)
            task_id += 1
            progress = True

            # Update assigned customers
            assigned_to_drone.update(task.customers())
            c_d -= set(task.customers())

        if not progress:
            break

    # Handle remaining forbidden customers that weren't served by standard NN
    # These need depot-based drone tasks. A single physical drone cannot start
    # from the depot multiple times, so only create depot fallback tasks for
    # drones that have not already been scheduled.
    remaining_forbidden = forbidden_customers - assigned_to_drone
    if remaining_forbidden:
        logger.info(
            f"Creating depot-based drone tasks for customers: {remaining_forbidden}")
        used_drones = {task.drone_id for task in tasks}
        for customer in remaining_forbidden:
            demand = demands.get(customer, 0.0)
            if demand > drone_capacity:
                logger.warning(
                    f"Customer {customer} demand {demand} exceeds drone capacity {drone_capacity}")
                continue

            # Find an available drone
            available_drone = None
            for d in drone_ids:
                if d not in used_drones:
                    available_drone = d
                    break

            if available_drone is None:
                continue

            # Create depot-to-depot drone task
            # payloads needs len(customers) + 1 entries: [delivery_to_customer, return_payload]
            payloads = [demand, 0.0] if demand > 0 else [0.0, 0.0]
            task = DroneTask(
                task_id=task_id,
                drone_id=available_drone,
                launch_truck=None,  # Depot launch
                launch_node=depot_start,
                customers=[customer],
                land_truck=None,  # Depot land
                retrieve_node=depot_end,
                payloads=payloads,
            )
            tasks.append(task)
            assigned_to_drone.add(customer)
            used_drones.add(available_drone)
            task_id += 1

    # Collect launch/retrieve nodes that must stay on truck routes
    sync_nodes: Set[int] = set()
    for task in tasks:
        sync_nodes.add(task.launch_node)
        sync_nodes.add(task.retrieve_node)

    # Update truck routes: remove drone-served customers but keep sync nodes
    for route_idx, route in enumerate(truck_routes):
        new_nodes = []
        for node in route_nodes[route_idx]:
            # Keep node if: not assigned to drone, or is depot, or is sync node
            if node not in assigned_to_drone or node in {depot_start, depot_end} or node in sync_nodes:
                new_nodes.append(node)
        # Ensure depot bookends
        if new_nodes and new_nodes[0] != depot_start:
            new_nodes.insert(0, depot_start)
        if new_nodes and new_nodes[-1] != depot_end:
            new_nodes.append(depot_end)
        # Remove consecutive duplicates
        compact = []
        for node in new_nodes:
            if not compact or compact[-1] != node:
                compact.append(node)
        route.nodes = compact

    return tasks


def _build_drone_subroute_nn(
    drone_id: int,
    route_nodes: List[List[int]],
    truck_routes: Sequence[TruckRoute],
    c_d: Set[int],
    assigned_to_drone: Set[int],
    drone_availability: Dict[int, Tuple[int, int]],
    demands: Mapping[int, float],
    node_index: Mapping[int, int],
    drone_matrix: Sequence[Sequence[float]],
    drone_time_matrix: Sequence[Sequence[float]],
    truck_time_matrix: Sequence[Sequence[float]],
    energy_model: DroneEnergyModel,
    battery_capacity: float,
    drone_capacity: float,
    deviation_rate: float,
    uncertainty_budget: float,
    instance: InstanceManager,
    same_truck_only: bool,
    task_id: int,
) -> DroneTask | None:
    """Build a drone sub-route using nearest neighbor principle.

    Steps:
    1. Find launch node (after previous retrieve point)
    2. Select nearest customer from C_D
    3. Find retrieve node (nearest truck node to customer)
    4. Try multi-visit extension
    """
    prev_route_idx, prev_pos = drone_availability.get(drone_id, (-1, -1))

    # Find available launch positions
    best_task = None
    best_cost_saving = float("-inf")

    for route_idx, nodes in enumerate(route_nodes):
        # Determine starting position for launch search
        if prev_route_idx == -1:
            start_pos = 0  # First task, start from depot
        elif prev_route_idx != route_idx:
            continue  # Drone continues from the truck where it last landed.
        elif prev_route_idx == route_idx:
            start_pos = prev_pos  # Continue after last retrieve

        for launch_pos in range(start_pos, len(nodes) - 1):
            launch_node = nodes[launch_pos]

            # Find nearest customer from C_D using nearest neighbor
            remaining_c_d = c_d - assigned_to_drone
            if not remaining_c_d:
                continue

            # Select nearest customer to launch node
            nearest_customer = _find_nearest_drone_customer(
                launch_node=launch_node,
                candidates=remaining_c_d,
                node_index=node_index,
                drone_matrix=drone_matrix,
            )

            if nearest_customer is None:
                continue

            # Try to build task with this customer (and possibly more)
            task_result = _try_build_multivisit_task(
                launch_node=launch_node,
                launch_pos=launch_pos,
                launch_route_idx=route_idx,
                first_customer=nearest_customer,
                route_nodes=route_nodes,
                truck_routes=truck_routes,
                c_d=c_d,
                assigned_to_drone=assigned_to_drone,
                demands=demands,
                node_index=node_index,
                drone_matrix=drone_matrix,
                drone_time_matrix=drone_time_matrix,
                truck_time_matrix=truck_time_matrix,
                energy_model=energy_model,
                battery_capacity=battery_capacity,
                drone_capacity=drone_capacity,
                deviation_rate=deviation_rate,
                uncertainty_budget=uncertainty_budget,
                instance=instance,
                same_truck_only=same_truck_only,
                drone_id=drone_id,
                task_id=task_id,
            )

            if task_result is not None:
                task, cost_saving, retrieve_route_idx, retrieve_pos = task_result
                if cost_saving > best_cost_saving:
                    best_cost_saving = cost_saving
                    best_task = (task, retrieve_route_idx, retrieve_pos)

    if best_task is None:
        return None

    task, retrieve_route_idx, retrieve_pos = best_task
    # Update drone availability
    drone_availability[drone_id] = (retrieve_route_idx, retrieve_pos)

    return task


def _find_nearest_drone_customer(
    launch_node: int,
    candidates: Set[int],
    node_index: Mapping[int, int],
    drone_matrix: Sequence[Sequence[float]],
) -> int | None:
    """Find nearest customer to launch node using drone distance.

    Note: Excludes launch_node itself from candidates to avoid self-selection.
    """
    i = node_index.get(launch_node)
    if i is None:
        return None

    nearest = None
    shortest = float("inf")

    for customer in candidates:
        # Skip launch_node to avoid selecting it as customer
        if customer == launch_node:
            continue
        j = node_index.get(customer)
        if j is None:
            continue
        dist = drone_matrix[i][j]
        if dist < shortest:
            shortest = dist
            nearest = customer

    return nearest


def _try_build_multivisit_task(
    launch_node: int,
    launch_pos: int,
    launch_route_idx: int,
    first_customer: int,
    route_nodes: List[List[int]],
    truck_routes: Sequence[TruckRoute],
    c_d: Set[int],
    assigned_to_drone: Set[int],
    demands: Mapping[int, float],
    node_index: Mapping[int, int],
    drone_matrix: Sequence[Sequence[float]],
    drone_time_matrix: Sequence[Sequence[float]],
    truck_time_matrix: Sequence[Sequence[float]],
    energy_model: DroneEnergyModel,
    battery_capacity: float,
    drone_capacity: float,
    deviation_rate: float,
    uncertainty_budget: float,
    instance: InstanceManager,
    same_truck_only: bool,
    drone_id: int,
    task_id: int,
) -> Tuple[DroneTask, float, int, int] | None:
    """Try to build a multi-visit drone task.

    Returns: (task, cost_saving, retrieve_route_idx, retrieve_pos) or None
    """
    customers: List[int] = [first_customer]
    current_load = demands.get(first_customer, 0.0)

    # Find retrieve node: nearest truck node to customer
    retrieve_result = _find_retrieve_node(
        customers=customers,
        launch_node=launch_node,
        launch_pos=launch_pos,
        launch_route_idx=launch_route_idx,
        route_nodes=route_nodes,
        node_index=node_index,
        drone_matrix=drone_matrix,
        same_truck_only=same_truck_only,
    )

    if retrieve_result is None:
        return None

    retrieve_node, retrieve_route_idx, retrieve_pos = retrieve_result

    # Check energy feasibility with robust constraint
    energy = _compute_robust_energy(
        launch=launch_node,
        customers=customers,
        retrieve=retrieve_node,
        demands=demands,
        energy_model=energy_model,
        time_matrix=drone_time_matrix,
        node_index=node_index,
        deviation_rate=deviation_rate,
        uncertainty_budget=uncertainty_budget,
    )

    if energy > battery_capacity:
        return None

    # Check time window feasibility
    if not _check_drone_time_feasibility(
        launch_node=launch_node,
        customers=customers,
        retrieve_node=retrieve_node,
        node_index=node_index,
        drone_time_matrix=drone_time_matrix,
        truck_time_matrix=truck_time_matrix,
        instance=instance,
    ):
        return None

    # Multi-visit extension: try to add more customers
    # Exclude launch_node from candidates (can't serve where we launch)
    remaining_c_d = (c_d - assigned_to_drone) - set(customers) - {launch_node}

    while remaining_c_d and current_load < drone_capacity:
        # Find nearest additional customer
        last_customer = customers[-1]
        next_customer = _find_nearest_drone_customer(
            launch_node=last_customer,  # Nearest to last visited
            candidates=remaining_c_d,
            node_index=node_index,
            drone_matrix=drone_matrix,
        )

        if next_customer is None:
            break

        # Check capacity
        next_demand = demands.get(next_customer, 0.0)
        if current_load + next_demand > drone_capacity:
            break

        # Try adding customer
        test_customers = customers + [next_customer]

        # Find new retrieve node
        new_retrieve_result = _find_retrieve_node(
            customers=test_customers,
            launch_node=launch_node,
            launch_pos=launch_pos,
            launch_route_idx=launch_route_idx,
            route_nodes=route_nodes,
            node_index=node_index,
            drone_matrix=drone_matrix,
            same_truck_only=same_truck_only,
        )

        if new_retrieve_result is None:
            break

        new_retrieve_node, new_retrieve_route_idx, new_retrieve_pos = new_retrieve_result

        # Check energy with new customer
        new_energy = _compute_robust_energy(
            launch=launch_node,
            customers=test_customers,
            retrieve=new_retrieve_node,
            demands=demands,
            energy_model=energy_model,
            time_matrix=drone_time_matrix,
            node_index=node_index,
            deviation_rate=deviation_rate,
            uncertainty_budget=uncertainty_budget,
        )

        if new_energy > battery_capacity:
            break

        # Check time window feasibility
        if not _check_drone_time_feasibility(
            launch_node=launch_node,
            customers=test_customers,
            retrieve_node=new_retrieve_node,
            node_index=node_index,
            drone_time_matrix=drone_time_matrix,
            truck_time_matrix=truck_time_matrix,
            instance=instance,
        ):
            break

        # Accept extension
        customers = test_customers
        current_load += next_demand
        retrieve_node = new_retrieve_node
        retrieve_route_idx = new_retrieve_route_idx
        retrieve_pos = new_retrieve_pos
        remaining_c_d.remove(next_customer)

    # Calculate cost saving
    truck_spec = instance.vehicle_specs.get("truck")
    drone_spec = instance.vehicle_specs.get("drone")
    truck_cost = truck_spec.unit_cost if truck_spec else 1.0
    drone_cost = drone_spec.unit_cost if drone_spec else 0.5

    # Truck distance saved (approximate)
    drone_path = [launch_node, *customers, retrieve_node]
    drone_distance = _path_distance(drone_matrix, drone_path, node_index)

    if drone_distance == float("inf"):
        return None

    # Simplified: just drone cost for now
    cost_saving = -drone_cost * drone_distance

    # Build task
    payloads = _build_payloads(customers, demands)
    task = DroneTask(
        task_id=task_id,
        drone_id=drone_id,
        launch_truck=truck_routes[launch_route_idx].id,
        launch_node=launch_node,
        customers=customers,
        land_truck=truck_routes[retrieve_route_idx].id,
        retrieve_node=retrieve_node,
        payloads=payloads,
    )

    return task, cost_saving, retrieve_route_idx, retrieve_pos


def _find_retrieve_node(
    customers: List[int],
    launch_node: int,
    launch_pos: int,
    launch_route_idx: int,
    route_nodes: List[List[int]],
    node_index: Mapping[int, int],
    drone_matrix: Sequence[Sequence[float]],
    same_truck_only: bool,
) -> Tuple[int, int, int] | None:
    """Find retrieve node: nearest truck node to last customer.

    Returns: (retrieve_node, route_idx, position) or None
    """
    last_customer = customers[-1]
    j = node_index.get(last_customer)
    if j is None:
        return None

    best_retrieve = None
    shortest = float("inf")

    for route_idx, nodes in enumerate(route_nodes):
        if same_truck_only and route_idx != launch_route_idx:
            continue

        # Retrieve must be after launch on same route
        start_pos = launch_pos + 1 if route_idx == launch_route_idx else 0

        for pos in range(start_pos, len(nodes)):
            node = nodes[pos]
            if node == launch_node:
                continue
            if node in customers:
                continue  # Can't retrieve at customer being served

            k = node_index.get(node)
            if k is None:
                continue

            dist = drone_matrix[j][k]
            if dist < shortest:
                shortest = dist
                best_retrieve = (node, route_idx, pos)

    return best_retrieve


def _compute_robust_energy(
    launch: int,
    customers: Sequence[int],
    retrieve: int,
    demands: Mapping[int, float],
    energy_model: DroneEnergyModel,
    time_matrix: Sequence[Sequence[float]],
    node_index: Mapping[int, int],
    deviation_rate: float,
    uncertainty_budget: float,
) -> float:
    """Compute robust (worst-case) energy consumption."""
    """Compute robust (worst-case) energy consumption."""
    if not customers:
        return 0.0

    nodes = [launch, *customers, retrieve]
    payloads = _build_payloads(customers, demands)

    nominal = 0.0
    deviations: List[float] = []

    for payload, start, end in zip(payloads, nodes, nodes[1:]):
        i = node_index.get(start)
        j = node_index.get(end)
        if i is None or j is None:
            return float("inf")

        travel_time = time_matrix[i][j]
        if travel_time == float("inf"):
            return float("inf")

        energy = energy_model.energy_kwh(payload, travel_time)
        nominal += energy
        deviations.append(energy * deviation_rate)

    # Budgeted sum: sum of largest deviations up to budget
    deviations.sort(reverse=True)
    budget_int = int(min(uncertainty_budget, len(deviations)))
    fractional = max(0.0, uncertainty_budget - budget_int)

    budgeted = sum(deviations[:budget_int])
    if fractional > 0 and budget_int < len(deviations):
        budgeted += fractional * deviations[budget_int]

    return nominal + budgeted


def _check_drone_time_feasibility(
    launch_node: int,
    customers: Sequence[int],
    retrieve_node: int,
    node_index: Mapping[int, int],
    drone_time_matrix: Sequence[Sequence[float]],
    truck_time_matrix: Sequence[Sequence[float]],
    instance: InstanceManager,
) -> bool:
    """Check if drone task respects time window constraints."""
    """Check if drone task respects time window constraints."""
    # Calculate drone arrival time at each customer
    nodes = [launch_node, *customers, retrieve_node]
    current_time = 0.0  # Assume launch at time 0 (simplified)

    for idx, (start, end) in enumerate(zip(nodes, nodes[1:])):
        i = node_index.get(start)
        j = node_index.get(end)
        if i is None or j is None:
            return False

        travel_time = drone_time_matrix[i][j]
        if travel_time == float("inf"):
            return False

        current_time += travel_time

        # Check time window for customers (not launch/retrieve)
        if idx < len(customers):
            customer = nodes[idx + 1]
            if customer in customers:
                tw_start, tw_end = instance.customer_manager.time_window(
                    customer)
                if tw_end is not None and current_time > tw_end:
                    return False

    return True
