"""Calibrate replay distribution parameters using existing best gamma solutions.

This script reuses `*_best.csv` outputs generated by
`sensitivity/instance10_gamma_multirun_replay.py`, reconstructs fixed solutions,
and runs replay parameter sweeps to maximize separability between gamma values.

Primary target:
- enlarge replay metric gaps between gamma_low (default 0) and gamma_high
  (default 3), especially `p0_all_served`.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Sequence
import argparse
import csv
import json
import math
import statistics
import sys

# Ensure project root is in sys.path for CLI runs.
PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import sys
from pathlib import Path
_project_root = Path(__file__).resolve().parent
for _p in [Path(__file__).resolve().parent] + list(Path(__file__).resolve().parents):
    if (_p / 'run_alns.py').exists():
        _project_root = _p
        break
if str(_project_root) not in sys.path:
    sys.path.insert(0, str(_project_root))
del _p, _project_root

from alns_vrpfd.evaluation import (
    GammaSolutionInput,
    ScenarioDistributionConfig,
    ScenarioReplayConfig,
    run_scenario_replay,
)
from alns_vrpfd.model.route import DroneTask, TruckRoute
from alns_vrpfd.model.solution import Solution
from alns_vrpfd.utils.io_utils import read_instance


@dataclass(frozen=True)
class ReplayCase:
    instance_name: str
    instance_path: Path
    instance: Any
    gamma_low_input: GammaSolutionInput
    gamma_high_input: GammaSolutionInput


@dataclass(frozen=True)
class Candidate:
    distribution: str
    candidate_id: str
    parameters: str
    is_baseline: bool
    config: ScenarioDistributionConfig


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Replay distribution calibration (gamma separability sweep)."
    )
    parser.add_argument(
        "--best-dir",
        type=str,
        default="sensitivity/results_new/scenario_replay",
        help="Directory containing per-instance *_best.csv files.",
    )
    parser.add_argument(
        "--best-glob",
        type=str,
        default="R_*_best.csv",
        help="Glob pattern for best files under --best-dir.",
    )
    parser.add_argument(
        "--distributions",
        type=str,
        default="ND,UD,NDC",
        help="Comma-separated set from ND,UD,NDC.",
    )
    parser.add_argument(
        "--gamma-low",
        type=int,
        default=0,
        help="Lower gamma for gap calculation.",
    )
    parser.add_argument(
        "--gamma-high",
        type=int,
        default=3,
        help="Higher gamma for gap calculation.",
    )
    parser.add_argument(
        "--scenario-count",
        type=int,
        default=600,
        help="Scenario count per candidate replay run.",
    )
    parser.add_argument(
        "--replay-seed",
        type=int,
        default=2024,
        help="Random seed for replay scenario generation.",
    )
    parser.add_argument(
        "--nd-cv-grid",
        type=str,
        default="0.08,0.10,0.12,0.15,0.18,0.22",
        help="CV grid for ND.",
    )
    parser.add_argument(
        "--ud-delta-grid",
        type=str,
        default="0.08,0.10,0.12,0.15,0.18,0.22",
        help="Delta grid for UD.",
    )
    parser.add_argument(
        "--ndc-cv-grid",
        type=str,
        default="0.08,0.10,0.12,0.15,0.18,0.22",
        help="CV grid for NDC.",
    )
    parser.add_argument(
        "--ndc-corr-grid",
        type=str,
        default="0.10,0.30,0.50,0.70,0.85",
        help="Correlation grid for NDC.",
    )
    parser.add_argument(
        "--energy-deviation-rate",
        type=float,
        default=None,
        help="Optional override for replay instance theta.",
    )
    parser.add_argument(
        "--max-instances",
        type=int,
        default=None,
        help="Optional limit on number of instances for quick dry-runs.",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="sensitivity/results_new/scenario_replay_calibration",
        help="Output directory for calibration csv files.",
    )
    return parser.parse_args()


def _parse_csv_floats(text: str, name: str) -> List[float]:
    vals: list[float] = []
    for token in text.split(","):
        token = token.strip()
        if not token:
            continue
        vals.append(float(token))
    if not vals:
        raise ValueError(f"{name} grid cannot be empty.")
    return vals


def _parse_dist_list(text: str) -> List[str]:
    vals = []
    for token in text.split(","):
        token = token.strip().upper()
        if token:
            vals.append(token)
    if not vals:
        raise ValueError("distributions list cannot be empty.")
    allowed = {"ND", "UD", "NDC"}
    bad = [x for x in vals if x not in allowed]
    if bad:
        raise ValueError(f"Unsupported distributions: {bad}. Allowed: {sorted(allowed)}")
    return vals


def _to_abs_instance_path(raw: str) -> Path:
    path = Path(raw)
    if path.is_absolute():
        return path
    return (PROJECT_ROOT / path).resolve()


def _float_or_inf(raw: str | None) -> float:
    if raw is None:
        return float("inf")
    text = raw.strip().lower()
    if text in {"", "inf", "infinity"}:
        return float("inf")
    return float(text)


def _is_truthy(raw: str | None) -> bool:
    if raw is None:
        return False
    return raw.strip().lower() in {"1", "true", "yes", "y"}


def _build_payloads(customers: Sequence[int], demands: Mapping[int, float]) -> List[float]:
    payloads: list[float] = []
    remaining = sum(demands.get(c, 0.0) for c in customers)
    payloads.append(remaining)
    for customer in customers:
        remaining -= demands.get(customer, 0.0)
        payloads.append(max(remaining, 0.0))
    return payloads


def _as_int_or_none(value: Any) -> int | None:
    if value is None:
        return None
    return int(value)


def _decode_solution_from_row(row: Mapping[str, str], instance: Any) -> Solution:
    truck_rows = json.loads(row["truck_routes"]) if row.get("truck_routes") else []
    drone_rows = json.loads(row["drone_tasks"]) if row.get("drone_tasks") else []

    demands = instance.customer_manager.demands()
    truck_spec = instance.vehicle_specs.get("truck")
    truck_capacity = float(truck_spec.capacity) if truck_spec is not None else float("inf")

    truck_routes: list[TruckRoute] = []
    for idx, payload in enumerate(truck_rows):
        nodes = [int(x) for x in payload.get("nodes", [])]
        if len(nodes) < 2:
            continue
        route_id = int(payload.get("truck_id", idx))
        current_load = sum(demands.get(node, 0.0) for node in nodes[1:-1])
        truck_routes.append(
            TruckRoute(
                route_id=route_id,
                nodes=nodes,
                capacity=truck_capacity,
                current_load=current_load,
            )
        )

    drone_tasks: list[DroneTask] = []
    for idx, payload in enumerate(drone_rows):
        customers = [int(x) for x in payload.get("customers", [])]
        drone_tasks.append(
            DroneTask(
                task_id=idx,
                drone_id=int(payload["drone_id"]),
                launch_truck=_as_int_or_none(payload.get("launch_truck")),
                launch_node=int(payload["launch_node"]),
                customers=customers,
                land_truck=_as_int_or_none(payload.get("land_truck")),
                retrieve_node=int(payload["retrieve_node"]),
                payloads=_build_payloads(customers, demands),
            )
        )

    return Solution(truck_routes=truck_routes, drone_tasks=drone_tasks)


def _load_rows_by_instance(
    best_files: Iterable[Path],
    gamma_low: int,
    gamma_high: int,
) -> Dict[Path, Dict[int, Mapping[str, str]]]:
    rows_by_instance: dict[Path, dict[int, Mapping[str, str]]] = {}
    for file in best_files:
        with file.open("r", encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f)
            for row in reader:
                if not row:
                    continue
                try:
                    gamma = int(float(row.get("gamma", "")))
                except (TypeError, ValueError):
                    continue
                if gamma not in {gamma_low, gamma_high}:
                    continue
                if not _is_truthy(row.get("feasible")):
                    continue
                instance_path = _to_abs_instance_path(row.get("instance", ""))
                if not instance_path.exists():
                    continue
                best_cost = _float_or_inf(row.get("best_cost"))
                if not math.isfinite(best_cost):
                    continue
                if not row.get("truck_routes"):
                    continue

                rows_by_gamma = rows_by_instance.setdefault(instance_path, {})
                old = rows_by_gamma.get(gamma)
                if old is None:
                    rows_by_gamma[gamma] = row
                else:
                    old_cost = _float_or_inf(old.get("best_cost"))
                    if best_cost < old_cost:
                        rows_by_gamma[gamma] = row
    return rows_by_instance


def _build_replay_cases(
    rows_by_instance: Mapping[Path, Mapping[int, Mapping[str, str]]],
    *,
    gamma_low: int,
    gamma_high: int,
    max_instances: int | None,
    energy_deviation_rate_override: float | None,
) -> List[ReplayCase]:
    deviation_rate = (
        float(energy_deviation_rate_override)
        if energy_deviation_rate_override is not None
        else 0.1
    )

    cases: list[ReplayCase] = []
    for instance_path in sorted(rows_by_instance.keys()):
        row_map = rows_by_instance[instance_path]
        if gamma_low not in row_map or gamma_high not in row_map:
            continue

        instance = read_instance(str(instance_path), strategy="class_based")
        if "drone" in instance.vehicle_specs:
            instance.vehicle_specs["drone"].endurance = float("inf")
        instance.configure_robustness(
            drone_battery_capacity=6.3,
            energy_uncertainty_budget=0,
            energy_deviation_rate=deviation_rate,

            same_truck_retrieval=False,
        )

        low_row = row_map[gamma_low]
        high_row = row_map[gamma_high]
        low_solution = _decode_solution_from_row(low_row, instance)
        high_solution = _decode_solution_from_row(high_row, instance)

        case = ReplayCase(
            instance_name=instance_path.stem,
            instance_path=instance_path,
            instance=instance,
            gamma_low_input=GammaSolutionInput(
                gamma=gamma_low,
                solution=low_solution,
                base_cost=float(low_row["best_cost"]),
            ),
            gamma_high_input=GammaSolutionInput(
                gamma=gamma_high,
                solution=high_solution,
                base_cost=float(high_row["best_cost"]),
            ),
        )
        cases.append(case)
        if max_instances is not None and len(cases) >= max_instances:
            break
    return cases


def _iter_candidates(
    dist_names: Sequence[str],
    nd_cvs: Sequence[float],
    ud_deltas: Sequence[float],
    ndc_cvs: Sequence[float],
    ndc_corrs: Sequence[float],
) -> List[Candidate]:
    candidates: list[Candidate] = []

    def _fmt(x: float) -> str:
        return f"{x:.3f}".rstrip("0").rstrip(".")

    if "ND" in dist_names:
        unique = sorted(set(nd_cvs + [0.1]))
        for cv in unique:
            candidates.append(
                Candidate(
                    distribution="ND",
                    candidate_id=f"ND_cv_{_fmt(cv)}",
                    parameters=f"cv={cv:.6f}",
                    is_baseline=abs(cv - 0.1) < 1e-12,
                    config=ScenarioDistributionConfig(
                        name=f"ND_cv_{_fmt(cv)}",
                        kind="ND",
                        cv=cv,
                    ),
                )
            )

    if "UD" in dist_names:
        unique = sorted(set(ud_deltas + [0.1]))
        for delta in unique:
            candidates.append(
                Candidate(
                    distribution="UD",
                    candidate_id=f"UD_delta_{_fmt(delta)}",
                    parameters=f"delta={delta:.6f}",
                    is_baseline=abs(delta - 0.1) < 1e-12,
                    config=ScenarioDistributionConfig(
                        name=f"UD_delta_{_fmt(delta)}",
                        kind="UD",
                        delta=delta,
                    ),
                )
            )

    if "NDC" in dist_names:
        unique_cv = sorted(set(ndc_cvs + [0.1]))
        unique_corr = sorted(set(ndc_corrs + [0.3]))
        for cv in unique_cv:
            for corr in unique_corr:
                candidates.append(
                    Candidate(
                        distribution="NDC",
                        candidate_id=f"NDC_cv_{_fmt(cv)}_corr_{_fmt(corr)}",
                        parameters=f"cv={cv:.6f};correlation={corr:.6f}",
                        is_baseline=(abs(cv - 0.1) < 1e-12 and abs(corr - 0.3) < 1e-12),
                        config=ScenarioDistributionConfig(
                            name=f"NDC_cv_{_fmt(cv)}_corr_{_fmt(corr)}",
                            kind="NDC",
                            cv=cv,
                            correlation=corr,
                        ),
                    )
                )

    return candidates


def _safe_pct(delta: float, base: float, cap_abs: float = 10.0) -> float:
    denom = abs(base) if abs(base) > 1e-9 else 1.0
    value = delta / denom
    return max(-cap_abs, min(cap_abs, value))


def _mean(values: Sequence[float]) -> float:
    if not values:
        return float("nan")
    return float(statistics.mean(values))


def _evaluate_candidate(
    candidate: Candidate,
    cases: Sequence[ReplayCase],
    *,
    gamma_low: int,
    gamma_high: int,
    scenario_count: int,
    replay_seed: int,
) -> tuple[list[Dict[str, Any]], Dict[str, Any]]:
    per_instance_rows: list[dict[str, Any]] = []
    for case in cases:
        replay = run_scenario_replay(
            instance=case.instance,
            gamma_solutions=[case.gamma_low_input, case.gamma_high_input],
            distributions=[candidate.config],
            config=ScenarioReplayConfig(
                scenario_count=scenario_count,
                seed=replay_seed,
                include_base_cost=True,
            ),
        )
        summary_by_gamma = {str(s.gamma): s for s in replay.summaries}
        low = summary_by_gamma.get(str(gamma_low))
        high = summary_by_gamma.get(str(gamma_high))
        if low is None or high is None:
            continue

        gap_p0 = high.p0_all_served - low.p0_all_served
        gap_unserved = low.avg_unserved - high.avg_unserved
        gap_no_takeoff = low.avg_no_takeoff - high.avg_no_takeoff
        gap_abort = low.avg_abort_return - high.avg_abort_return
        gap_avg_cost = high.avg_cost - low.avg_cost
        gap_std_cost = high.std_cost - low.std_cost
        gap_avg_cost_pct = _safe_pct(gap_avg_cost, low.avg_cost)
        gap_std_cost_pct = _safe_pct(gap_std_cost, low.std_cost)

        abs_stats_gap = (
            abs(gap_p0)
            + abs(gap_unserved)
            + abs(gap_no_takeoff)
            + abs(gap_abort)
            + abs(gap_avg_cost_pct)
            + abs(gap_std_cost_pct)
        )
        signed_service_gap = gap_p0 + gap_unserved + gap_no_takeoff + gap_abort
        composite_score = 2.0 * signed_service_gap + abs_stats_gap

        per_instance_rows.append(
            {
                "distribution": candidate.distribution,
                "candidate_id": candidate.candidate_id,
                "parameters": candidate.parameters,
                "is_baseline": int(candidate.is_baseline),
                "instance": case.instance_name,
                "gap_p0_all_served": gap_p0,
                "gap_avg_unserved": gap_unserved,
                "gap_avg_no_takeoff": gap_no_takeoff,
                "gap_avg_abort_return": gap_abort,
                "gap_avg_cost": gap_avg_cost,
                "gap_std_cost": gap_std_cost,
                "gap_avg_cost_pct": gap_avg_cost_pct,
                "gap_std_cost_pct": gap_std_cost_pct,
                "g0_avg_cost": low.avg_cost,
                "g3_avg_cost": high.avg_cost,
                "g0_std_cost": low.std_cost,
                "g3_std_cost": high.std_cost,
                "g0_p0_all_served": low.p0_all_served,
                "g3_p0_all_served": high.p0_all_served,
                "abs_stats_gap": abs_stats_gap,
                "signed_service_gap": signed_service_gap,
                "composite_score": composite_score,
            }
        )

    agg: dict[str, Any] = {
        "distribution": candidate.distribution,
        "candidate_id": candidate.candidate_id,
        "parameters": candidate.parameters,
        "is_baseline": int(candidate.is_baseline),
        "instance_count": len(per_instance_rows),
    }
    metric_names = [
        "gap_p0_all_served",
        "gap_avg_unserved",
        "gap_avg_no_takeoff",
        "gap_avg_abort_return",
        "gap_avg_cost",
        "gap_std_cost",
        "gap_avg_cost_pct",
        "gap_std_cost_pct",
        "abs_stats_gap",
        "signed_service_gap",
        "composite_score",
    ]
    for m in metric_names:
        agg[f"mean_{m}"] = _mean([float(row[m]) for row in per_instance_rows])

    if per_instance_rows:
        agg["share_positive_p0_gap"] = (
            sum(1 for row in per_instance_rows if float(row["gap_p0_all_served"]) > 0.0)
            / len(per_instance_rows)
        )
    else:
        agg["share_positive_p0_gap"] = float("nan")
    return per_instance_rows, agg


def _write_csv(path: Path, rows: Sequence[Mapping[str, Any]], fieldnames: Sequence[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(fieldnames))
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def main() -> None:
    args = parse_args()
    dist_names = _parse_dist_list(args.distributions)
    nd_cvs = _parse_csv_floats(args.nd_cv_grid, "nd_cv_grid")
    ud_deltas = _parse_csv_floats(args.ud_delta_grid, "ud_delta_grid")
    ndc_cvs = _parse_csv_floats(args.ndc_cv_grid, "ndc_cv_grid")
    ndc_corrs = _parse_csv_floats(args.ndc_corr_grid, "ndc_corr_grid")

    best_dir = (PROJECT_ROOT / args.best_dir).resolve()
    best_files = sorted(best_dir.glob(args.best_glob))
    if not best_files:
        raise FileNotFoundError(f"No best files found in {best_dir} by glob {args.best_glob}")

    rows_by_instance = _load_rows_by_instance(
        best_files=best_files,
        gamma_low=args.gamma_low,
        gamma_high=args.gamma_high,
    )
    cases = _build_replay_cases(
        rows_by_instance=rows_by_instance,
        gamma_low=args.gamma_low,
        gamma_high=args.gamma_high,
        max_instances=args.max_instances,
        energy_deviation_rate_override=args.energy_deviation_rate,
    )
    if not cases:
        raise RuntimeError("No valid replay cases were built. Check best files and gamma filters.")

    candidates = _iter_candidates(
        dist_names=dist_names,
        nd_cvs=nd_cvs,
        ud_deltas=ud_deltas,
        ndc_cvs=ndc_cvs,
        ndc_corrs=ndc_corrs,
    )
    if not candidates:
        raise RuntimeError("No calibration candidates to evaluate.")

    print("=" * 96)
    print("Replay distribution parameter calibration")
    print("=" * 96)
    print(f"best_dir: {best_dir}")
    print(f"best_glob: {args.best_glob}")
    print(f"cases: {len(cases)}")
    print(f"distributions: {dist_names}")
    print(f"candidates: {len(candidates)}")
    print(f"gamma pair: {args.gamma_low} vs {args.gamma_high}")
    print(f"scenario_count: {args.scenario_count}")
    print(f"replay_seed: {args.replay_seed}")

    all_instance_rows: list[dict[str, Any]] = []
    ranking_rows: list[dict[str, Any]] = []

    for idx, cand in enumerate(candidates, 1):
        print(f"[{idx}/{len(candidates)}] {cand.candidate_id}")
        per_instance, agg = _evaluate_candidate(
            candidate=cand,
            cases=cases,
            gamma_low=args.gamma_low,
            gamma_high=args.gamma_high,
            scenario_count=args.scenario_count,
            replay_seed=args.replay_seed,
        )
        all_instance_rows.extend(per_instance)
        ranking_rows.append(agg)

    ranking_rows.sort(
        key=lambda row: (
            row["distribution"],
            -float(row.get("mean_composite_score", float("-inf"))),
            -float(row.get("mean_gap_p0_all_served", float("-inf"))),
        )
    )

    output_dir = (PROJECT_ROOT / args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    instance_fields = [
        "distribution",
        "candidate_id",
        "parameters",
        "is_baseline",
        "instance",
        "gap_p0_all_served",
        "gap_avg_unserved",
        "gap_avg_no_takeoff",
        "gap_avg_abort_return",
        "gap_avg_cost",
        "gap_std_cost",
        "gap_avg_cost_pct",
        "gap_std_cost_pct",
        "g0_avg_cost",
        "g3_avg_cost",
        "g0_std_cost",
        "g3_std_cost",
        "g0_p0_all_served",
        "g3_p0_all_served",
        "abs_stats_gap",
        "signed_service_gap",
        "composite_score",
    ]
    ranking_fields = [
        "distribution",
        "candidate_id",
        "parameters",
        "is_baseline",
        "instance_count",
        "mean_gap_p0_all_served",
        "mean_gap_avg_unserved",
        "mean_gap_avg_no_takeoff",
        "mean_gap_avg_abort_return",
        "mean_gap_avg_cost",
        "mean_gap_std_cost",
        "mean_gap_avg_cost_pct",
        "mean_gap_std_cost_pct",
        "mean_abs_stats_gap",
        "mean_signed_service_gap",
        "mean_composite_score",
        "share_positive_p0_gap",
    ]
    _write_csv(output_dir / "calibration_instance_metrics.csv", all_instance_rows, instance_fields)
    _write_csv(output_dir / "calibration_ranking.csv", ranking_rows, ranking_fields)

    rec_rows: list[dict[str, Any]] = []
    for dist in dist_names:
        subset = [row for row in ranking_rows if row["distribution"] == dist]
        if not subset:
            continue
        subset.sort(
            key=lambda row: (
                -float(row["mean_composite_score"]),
                -float(row["mean_gap_p0_all_served"]),
            )
        )
        baseline = next((row for row in subset if int(row["is_baseline"]) == 1), None)
        base_score = float(baseline["mean_composite_score"]) if baseline else float("nan")
        for rank, row in enumerate(subset[:5], 1):
            current_score = float(row["mean_composite_score"])
            rec_rows.append(
                {
                    "distribution": dist,
                    "rank": rank,
                    "candidate_id": row["candidate_id"],
                    "parameters": row["parameters"],
                    "is_baseline": row["is_baseline"],
                    "mean_composite_score": current_score,
                    "mean_gap_p0_all_served": row["mean_gap_p0_all_served"],
                    "mean_gap_avg_unserved": row["mean_gap_avg_unserved"],
                    "mean_gap_avg_no_takeoff": row["mean_gap_avg_no_takeoff"],
                    "mean_gap_avg_abort_return": row["mean_gap_avg_abort_return"],
                    "mean_abs_stats_gap": row["mean_abs_stats_gap"],
                    "share_positive_p0_gap": row["share_positive_p0_gap"],
                    "score_gain_vs_baseline": (current_score - base_score) if math.isfinite(base_score) else float("nan"),
                }
            )
    rec_fields = [
        "distribution",
        "rank",
        "candidate_id",
        "parameters",
        "is_baseline",
        "mean_composite_score",
        "mean_gap_p0_all_served",
        "mean_gap_avg_unserved",
        "mean_gap_avg_no_takeoff",
        "mean_gap_avg_abort_return",
        "mean_abs_stats_gap",
        "share_positive_p0_gap",
        "score_gain_vs_baseline",
    ]
    _write_csv(output_dir / "calibration_recommendations_top5.csv", rec_rows, rec_fields)

    print("\nTop-3 candidates per distribution:")
    for dist in dist_names:
        subset = [row for row in ranking_rows if row["distribution"] == dist]
        if not subset:
            continue
        subset.sort(
            key=lambda row: (
                -float(row["mean_composite_score"]),
                -float(row["mean_gap_p0_all_served"]),
            )
        )
        print(f"\n[{dist}]")
        for row in subset[:3]:
            print(
                f"  {row['candidate_id']:<24} "
                f"score={float(row['mean_composite_score']):.4f}  "
                f"gap_p0={float(row['mean_gap_p0_all_served']):.4f}  "
                f"gap_unserved={float(row['mean_gap_avg_unserved']):.4f}"
            )

    print("\nOutputs:")
    print(f"- {output_dir / 'calibration_instance_metrics.csv'}")
    print(f"- {output_dir / 'calibration_ranking.csv'}")
    print(f"- {output_dir / 'calibration_recommendations_top5.csv'}")


if __name__ == "__main__":
    main()
